# Generated by Django 3.0.5 on 2020-05-08 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlackChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('webhook_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SlackUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('slack_id', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='SlackMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=127, unique=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='slack.SlackChannel')),
                ('users', models.ManyToManyField(to='slack.SlackUser')),
            ],
        ),
    ]
