# Generated by Django 3.0.6 on 2020-05-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slack", "0002_create_messages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slackmessage",
            name="users",
            field=models.ManyToManyField(blank=True, to="slack.SlackUser"),
        ),
    ]
