# Generated by Django 5.1.1 on 2025-02-04 04:21

from django.db import migrations


def create_messages(apps, schema_editor):
    """
    Create Slack messages to ensure they're never missing
    """
    SlackChannel = apps.get_model("slack", "SlackChannel")
    channel, _ = SlackChannel.objects.get_or_create(
        name="Example", webhook_url="https://example.com"
    )

    SlackMessage = apps.get_model("slack", "SlackMessage")
    SlackMessage.objects.get_or_create(
        slug="coordinator-task", defaults={"channel": channel}
    )


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0005_create_messages"),
    ]

    operations = [migrations.RunPython(create_messages)]
