# Generated by Django 3.2.6 on 2021-08-18 05:54

from django.db import migrations


GROUPS_TO_REMOVE = [
    "Developer",
    "Impact",
    "Volunteer",
]

GROUPS_TO_ADD = {
    "Admin": [
        "view_accesstoken",
        "add_actiondocument",
        "change_actiondocument",
        "delete_actiondocument",
        "view_actiondocument",
    ],
    "Coordinator": [
        "view_accesstoken",
        "add_actiondocument",
        "change_actiondocument",
        "delete_actiondocument",
        "view_actiondocument",
    ],
    "Paralegal": [],
}


def add_case_permission_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    for groupname in GROUPS_TO_REMOVE:
        Group.objects.filter(name=groupname).delete()

    for groupname, permission_codenames in GROUPS_TO_ADD.items():
        group, _ = Group.objects.get_or_create(name=groupname)
        for codename in permission_codenames:
            permission = Permission.objects.get(codename=codename)
            group.permissions.add(permission)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_is_intern"),
    ]

    operations = [
        migrations.RunPython(add_case_permission_groups),
    ]
