# Generated by Django 3.2.12 on 2022-03-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_ms_account_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="case_capacity",
            field=models.PositiveIntegerField(default=4),
        ),
    ]
