# Generated by Django 4.0.10 on 2023-11-16 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_university_user_university'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'universities'},
        ),
    ]
