# Generated by Django 5.1.1 on 2024-09-16 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_university_options"),
    ]

    operations = [
        migrations.RunSQL(
            """ALTER TABLE IF EXISTS social_auth_usersocialauth
                 ALTER COLUMN extra_data SET DATA TYPE jsonb
                 USING
                   extra_data::jsonb;"""
        )
    ]
