# Generated by Django 4.0.10 on 2024-08-15 23:09

from django.db import migrations, models


def _set_coordinator_as_system_account(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(username="coordinators@anikalegal.com").update(
        is_system_account=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_university_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_system_account",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            _set_coordinator_as_system_account,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
