# Generated by Django 5.1.1 on 2026-04-08 06:28

import logging

from django.db import migrations

logger = logging.getLogger("migration")


def _change_user_email_and_username_domain(apps, schema_editor):
    User = apps.get_model("accounts", "User")

    for user in User.objects.all():
        if user.email and user.email.endswith("@anikalegal.com"):
            logger.info("Changing email and username domain for user %s", user.email)
            user.email = user.email.replace("@anikalegal.com", "@anikalegal.org.au")
            user.username = user.username.replace(
                "@anikalegal.com", "@anikalegal.org.au"
            )
            user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_alter_social_auth_usersocialauth_extra_data"),
    ]

    operations = [
        migrations.RunPython(
            _change_user_email_and_username_domain,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
