# Generated by Django 5.1.1 on 2026-05-06 03:45

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_social_auth_usersocialauth_extra_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ms_account_initial_password",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=255, null=True
            ),
        ),
    ]
