# Generated by Django 3.1.3 on 2020-11-10 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('phone_number', models.CharField(max_length=32)),
                ('topic', models.CharField(max_length=1)),
                ('requires_callback', models.BooleanField(default=False)),
                ('number_callbacks', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
