# Generated by Django 3.1.3 on 2021-02-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0003_auto_20201204_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
