# Generated by Django 3.2.12 on 2022-02-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0006_alter_call_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='topic',
            field=models.CharField(choices=[('REPAIRS', 'Repairs'), ('BONDS', 'Bonds'), ('RENT_REDUCTION', 'Rent reduction'), ('EVICTION', 'Eviction'), ('OTHER', 'Other')], max_length=32),
        ),
    ]
