# Generated by Django 4.0.10 on 2024-01-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0009_alter_call_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
