# Generated by Django 5.1.1 on 2025-04-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caller", "0011_alter_call_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="call",
            name="topic",
            field=models.CharField(
                choices=[
                    ("REPAIRS", "Repairs"),
                    ("BONDS", "Bonds"),
                    ("EVICTION_ARREARS", "Eviction (Arrears)"),
                    ("EVICTION_RETALIATORY", "Eviction (Retaliatory)"),
                    ("HEALTH_CHECK", "Housing Health Check"),
                    ("RENT_REDUCTION", "Rent reduction"),
                    ("OTHER", "Other"),
                ],
                max_length=32,
            ),
        ),
    ]
