# Generated by Django 3.2.5 on 2021-07-20 03:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.uploads


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_addr", models.EmailField(max_length=254)),
                ("to_addr", models.EmailField(max_length=254)),
                ("to_addrs", models.TextField()),
                ("cc_addrs", models.TextField(default="")),
                ("subject", models.CharField(max_length=1024)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("READY_TO_SEND", "Ready to send"),
                            ("SENT", "Sent"),
                            ("RECEIVED", "Received"),
                        ],
                        max_length=32,
                    ),
                ),
                ("text", models.TextField()),
                ("html", models.TextField(default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="EmailAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to=utils.uploads.get_s3_key)),
                ("content_type", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "email",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="emails.email",
                    ),
                ),
            ],
        ),
    ]