# Generated by Django 3.2.6 on 2021-08-29 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.uploads


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0036_alter_issuenote_note_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_addr', models.EmailField(max_length=254)),
                ('to_addr', models.EmailField(blank=True, default=None, max_length=254)),
                ('to_addrs', models.TextField()),
                ('cc_addrs', models.TextField(default='')),
                ('subject', models.CharField(max_length=1024)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('READY_TO_SEND', 'Ready to send'), ('SENT', 'Sent'), ('RECEIVED', 'Received'), ('INGESTED', 'Ingested')], max_length=32)),
                ('text', models.TextField()),
                ('html', models.TextField(default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.issue')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_email', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=utils.uploads.get_s3_key)),
                ('content_type', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='emails.email')),
            ],
        ),
    ]
