# Generated by Django 3.2.6 on 2021-08-31 07:10

from django.conf import settings
import django.contrib.postgres.fields
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_issuenote_note_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='cc_addrs',
        ),
        migrations.RemoveField(
            model_name='email',
            name='from_addr',
        ),
        migrations.RemoveField(
            model_name='email',
            name='html',
        ),
        migrations.RemoveField(
            model_name='email',
            name='to_addr',
        ),
        migrations.RemoveField(
            model_name='email',
            name='to_addrs',
        ),
        migrations.AddField(
            model_name='email',
            name='cc_addresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='email',
            name='from_address',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='email',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.issue'),
        ),
        migrations.AddField(
            model_name='email',
            name='received_data',
            field=models.JSONField(default={}, encoder=django.core.serializers.json.DjangoJSONEncoder),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_email', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='email',
            name='to_address',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='email',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('READY_TO_SEND', 'Ready to send'), ('SENT', 'Sent'), ('RECEIVED', 'Received'), ('INGESTED', 'Ingested')], max_length=32),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='email',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='emailattachment',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='emails.email'),
        ),
    ]
