# Generated by Django 3.2.7 on 2021-09-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20210831_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='html',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='email',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('READY_TO_SEND', 'Ready to send'), ('SENT', 'Sent'), ('RECEIVED', 'Received'), ('INGESTED', 'Ingested'), ('INGEST_FAILURE', 'Ingest failed')], max_length=32),
        ),
    ]
