# Generated by Django 3.2.7 on 2021-09-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_email_actionstep_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailattachment',
            name='actionstep_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
