# Generated by Django 3.2.7 on 2021-09-12 04:22

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_emailattachment_actionstep_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='received_data',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
