# Generated by Django 3.2.7 on 2021-09-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0007_alter_email_received_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
