# Generated by Django 3.2.7 on 2021-11-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0008_email_processed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
