# Generated by Django 3.2.7 on 2021-11-16 23:35

from django.db import migrations


def set_is_alert_sent(apps, schema_editor):
    Email = apps.get_model("emails", "Email")
    Email.objects.all().update(is_alert_sent=True)


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0009_email_is_alert_sent"),
    ]

    operations = [
        migrations.RunPython(set_is_alert_sent),
    ]
