# Generated by Django 4.0.4 on 2022-05-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0012_emailtemplate_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailattachment',
            name='sharepoint_state',
            field=models.CharField(choices=[('NOT_UPLOADED', 'Not uploaded'), ('UPLOADING', 'Uploading'), ('UPLOADED', 'Uploaded')], default='NOT_UPLOADED', max_length=16),
        ),
    ]
