# Generated by Django 4.0.4 on 2022-07-12 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0012_emailtemplate_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
