# Generated by Django 4.0.4 on 2022-05-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0013_emailattachment_sharepoint_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='topic',
            field=models.CharField(choices=[('GENERAL', 'General'), ('REPAIRS', 'Repairs'), ('BONDS', 'Bonds'), ('RENT_REDUCTION', 'Rent reduction'), ('EVICTION', 'Eviction'), ('OTHER', 'Other')], max_length=32),
        ),
    ]
