# Generated by Django 4.0.6 on 2022-07-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0014_alter_emailtemplate_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='sendgrid_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='email',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('READY_TO_SEND', 'Ready to send'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('DELIVERY_FAILURE', 'Delivery failed'), ('RECEIVED', 'Received'), ('INGESTED', 'Ingested'), ('INGEST_FAILURE', 'Ingest failed')], max_length=32),
        ),
    ]
