# Generated by Django 4.0.7 on 2022-08-21 05:10

from django.db import migrations


def shorten_message_id(apps, schema_editor):
    Email = apps.get_model("emails", "Email")
    for email in Email.objects.all():
        if email.sendgrid_id:
            email.sendgrid_id = email.sendgrid_id.split(".")[0]
            email.save()


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0015_email_sendgrid_id_alter_email_state"),
    ]

    operations = [
        migrations.RunPython(shorten_message_id),
    ]
