# Generated by Django 5.1.1 on 2025-04-03 23:01

import utils.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0017_alter_emailtemplate_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailattachment",
            name="file",
            field=models.FileField(max_length=1088, upload_to=utils.uploads.get_s3_key),
        ),
    ]
