# Generated by Django 5.1.1 on 2025-06-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0020_alter_emailtemplate_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="name",
            field=models.CharField(db_collation="natural", max_length=64),
        ),
    ]
