# Generated by Django 5.1.1 on 2025-09-03 04:43

import re

from django.db import migrations, models
from django.utils.text import slugify
from utils.signals import DisableSignals


def _populate_thread_name_field(apps, schema_editor):
    Email = apps.get_model("emails", "Email")
    with DisableSignals():
        for email in Email.objects.all().iterator():
            email.thread_name = slugify(
                re.sub(r"re\s*:\s*", "", email.subject, flags=re.IGNORECASE)
            )
            email.save()


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0021_alter_emailtemplate_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="thread_name",
            field=models.SlugField(blank=True, default="", max_length=1024),
        ),
        migrations.RunPython(_populate_thread_name_field),
    ]
