# Generated by Django 5.1.1 on 2025-09-04 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0022_email_thread_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailattachment",
            name="email",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="emails.email",
            ),
        ),
    ]
