# Generated by Django 5.1.1 on 2025-09-09 00:24

import django.core.serializers.json
import django.db.models.deletion
import emails.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0023_alter_emailattachment_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceivedEmail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "received_data",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceivedAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                (
                    "file",
                    models.FileField(
                        max_length=1088,
                        storage=emails.models.ReceivedAttachment._get_storage_class,
                        upload_to=emails.models.ReceivedAttachment._get_upload_to,
                    ),
                ),
                ("content_type", models.CharField(max_length=128)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="emails.receivedemail",
                    ),
                ),
            ],
        ),
    ]
