# Generated by Django 5.1.1 on 2025-09-12 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0023_alter_emailattachment_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailattachment",
            name="email",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="emails.email",
            ),
        ),
    ]
