# Generated by Django 5.1.1 on 2025-09-15 11:26

import hashlib
import json

from django.db import migrations, models
from utils.signals import DisableSignals


def _populate_received_data_table(apps, schema_editor):
    Email = apps.get_model("emails", "Email")

    with DisableSignals():
        for email in Email.objects.filter(received_data__isnull=False).iterator():
            email.received_data_hash = hashlib.sha256(
                json.dumps(email.received_data, sort_keys=True).encode()
            ).hexdigest()
            email.save()


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0024_alter_emailattachment_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="received_data_hash",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="email",
            name="state",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("READY_TO_SEND", "Ready to send"),
                    ("SENT", "Sent"),
                    ("DELIVERED", "Delivered"),
                    ("DELIVERY_FAILURE", "Delivery failed"),
                    ("SAVED", "Saved"),
                    ("RECEIVED", "Received"),
                    ("INGESTED", "Ingested"),
                    ("INGEST_FAILURE", "Ingest failed"),
                ],
                max_length=32,
            ),
        ),
        migrations.RunPython(_populate_received_data_table),
    ]
