# Generated by Django 5.1.1 on 2025-09-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0026_remove_duplicate_emails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="received_data_hash",
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
