# Generated by Django 3.2.3 on 2021-05-20 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210520_1855'),
    ]

    operations = [
    ]
