# Generated by Django 3.2.3 on 2021-05-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210520_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='published_at',
        ),
    ]
