# Generated by Django 3.2.3 on 2021-05-27 03:05

from django.db import migrations


def setup_default_site(apps, schema_editor):
    RootPage = apps.get_model("web", "RootPage")
    BlogListPage = apps.get_model("web", "BlogListPage")
    ResourceListPage = apps.get_model("web", "ResourceListPage")

    Site = apps.get_model("wagtailcore", "Site")
    Page = apps.get_model("wagtailcore", "Page")
    Locale = apps.get_model("wagtailcore", "Locale")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Site.objects.all().delete()
    Page.objects.all().delete()
    page_data = {
        "title": "Anika Content Management System",
        "content_type": ContentType.objects.get_for_model(RootPage),
        "locale": Locale.objects.first(),
        "slug": "root",
        "path": "0001",
        "depth": 1,
        "numchild": 0,
        "url_path": "/",
    }
    root_page = RootPage.objects.create(**page_data)
    site_data = {
        "hostname": "localhost",
        "port": 80,
        "site_name": "Anika Legal",
        "root_page": root_page,
        "is_default_site": True,
    }
    Site.objects.create(**site_data)


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_resourcelistpage_resourcepage_rootpage"),
    ]

    operations = [
        migrations.RunPython(setup_default_site),
    ]
