# Generated by Django 3.2.3 on 2021-06-03 03:38

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_auto_20210527_1305"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="full title")),
                    (
                        "paragraph",
                        wagtail.blocks.RichTextBlock(
                            features=["h2", "bold", "italic", "ol", "ul", "link"]
                        ),
                    ),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    ("quote", wagtail.blocks.BlockQuoteBlock()),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="resourcepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="full title")),
                    (
                        "paragraph",
                        wagtail.blocks.RichTextBlock(
                            features=["h2", "bold", "italic", "ol", "ul", "link"]
                        ),
                    ),
                ]
            ),
        ),
    ]
