# Generated by Django 3.2.3 on 2021-06-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20210603_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebRedirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.CharField(max_length=2048)),
                ('destination_path', models.CharField(max_length=2048)),
                ('is_permanent', models.BooleanField()),
            ],
        ),
    ]
