# Generated by Django 3.2.3 on 2021-06-29 06:26

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0010_joblistpage_jobpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpage",
            name="closing_date",
            field=models.DateField(
                default=datetime.datetime(
                    2021, 6, 29, 6, 26, 57, 349840, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
