# Generated by Django 3.2.10 on 2022-01-19 04:23

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0016_volunteerpage_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpage",
            name="icon",
            field=models.CharField(
                choices=[
                    ("web/img/icons/personal-growth.svg", "personal-growth"),
                    ("web/img/icons/reports.svg", "reports"),
                    ("web/img/icons/impact.svg", "impact"),
                    ("web/img/icons/email.svg", "email"),
                    ("web/img/icons/clients.svg", "clients"),
                    ("web/img/icons/dial.svg", "dial"),
                    ("web/img/icons/house.svg", "house"),
                    ("web/img/icons/cash.svg", "cash"),
                    ("web/img/icons/crowd.svg", "crowd"),
                    ("web/img/icons/law.svg", "law"),
                    ("web/img/icons/network.svg", "network"),
                    ("web/img/icons/students.svg", "students"),
                    ("web/img/icons/document.svg", "document"),
                    ("web/img/icons/love-hand.svg", "love-hand"),
                    ("web/img/icons/social", "social"),
                    ("web/img/icons/questionnaire.svg", "questionnaire"),
                    ("web/img/icons/star.svg", "star"),
                    ("web/img/icons/phone.svg", "phone"),
                    ("web/img/icons/tree.svg", "tree"),
                    ("web/img/icons/fast.svg", "fast"),
                    ("web/img/icons/team.svg", "team"),
                    ("web/img/icons/change.svg", "change"),
                    ("web/img/icons/wrench.svg", "wrench"),
                    ("web/img/icons/partners.svg", "partners"),
                    ("web/img/icons/universities.svg", "universities"),
                    ("web/img/icons/lawyer.svg", "lawyer"),
                    ("web/img/icons/valet.svg", "valet"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="volunteerpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="full title")),
                    (
                        "paragraph",
                        wagtail.blocks.RichTextBlock(
                            features=["h2", "bold", "italic", "ol", "ul", "link"]
                        ),
                    ),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    ("quote", wagtail.blocks.BlockQuoteBlock()),
                    (
                        "attributed_quote",
                        wagtail.blocks.StructBlock(
                            [
                                ("quote", wagtail.blocks.CharBlock()),
                                ("source", wagtail.blocks.CharBlock()),
                            ]
                        ),
                    ),
                ]
            ),
        ),
    ]
