# Generated by Django 4.0.4 on 2022-07-14 00:36

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_dashboarditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['h3', 'bold', 'italic', 'ol', 'ul', 'link'])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('quote', wagtail.core.blocks.BlockQuoteBlock())]),
        ),
        migrations.AlterField(
            model_name='jobpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['h3', 'bold', 'italic', 'ol', 'ul', 'link'])), ('image', wagtail.images.blocks.ImageChooserBlock())]),
        ),
        migrations.AlterField(
            model_name='jobpage',
            name='icon',
            field=models.CharField(choices=[('web/img/icons/cash.svg', 'cash'), ('web/img/icons/change.svg', 'change'), ('web/img/icons/clients.svg', 'clients'), ('web/img/icons/crowd.svg', 'crowd'), ('web/img/icons/dial.svg', 'dial'), ('web/img/icons/document.svg', 'document'), ('web/img/icons/email.svg', 'email'), ('web/img/icons/fast.svg', 'fast'), ('web/img/icons/house.svg', 'house'), ('web/img/icons/impact.svg', 'impact'), ('web/img/icons/law.svg', 'law'), ('web/img/icons/lawyer.svg', 'lawyer'), ('web/img/icons/love-hand.svg', 'love-hand'), ('web/img/icons/network.svg', 'network'), ('web/img/icons/partners.svg', 'partners'), ('web/img/icons/personal-growth.svg', 'personal-growth'), ('web/img/icons/phone.svg', 'phone'), ('web/img/icons/questionnaire.svg', 'questionnaire'), ('web/img/icons/reports.svg', 'reports'), ('web/img/icons/social', 'social'), ('web/img/icons/star.svg', 'star'), ('web/img/icons/students.svg', 'students'), ('web/img/icons/team.svg', 'team'), ('web/img/icons/tree.svg', 'tree'), ('web/img/icons/universities.svg', 'universities'), ('web/img/icons/valet.svg', 'valet'), ('web/img/icons/wrench.svg', 'wrench')], max_length=64),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['h3', 'bold', 'italic', 'ol', 'ul', 'link'])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('quote', wagtail.core.blocks.BlockQuoteBlock())]),
        ),
        migrations.AlterField(
            model_name='resourcepage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['h3', 'bold', 'italic', 'ol', 'ul', 'link']))]),
        ),
        migrations.AlterField(
            model_name='volunteerpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['h3', 'bold', 'italic', 'ol', 'ul', 'link'])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('quote', wagtail.core.blocks.BlockQuoteBlock()), ('attributed_quote', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.CharBlock()), ('source', wagtail.core.blocks.CharBlock())]))]),
        ),
    ]
