# Generated by Django 4.0.4 on 2022-05-17 01:48

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_dashboarditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock(features=['h3', 'bold', 'italic', 'ol', 'ul', 'link'])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('quote', wagtail.blocks.BlockQuoteBlock())]),
        ),
        migrations.AlterField(
            model_name='jobpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock(features=['h3', 'bold', 'italic', 'ol', 'ul', 'link'])), ('image', wagtail.images.blocks.ImageChooserBlock())]),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock(features=['h3', 'bold', 'italic', 'ol', 'ul', 'link'])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('quote', wagtail.blocks.BlockQuoteBlock())]),
        ),
        migrations.AlterField(
            model_name='resourcepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock(features=['h3', 'bold', 'italic', 'ol', 'ul', 'link']))]),
        ),
        migrations.AlterField(
            model_name='volunteerpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock(features=['h3', 'bold', 'italic', 'ol', 'ul', 'link'])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('quote', wagtail.blocks.BlockQuoteBlock()), ('attributed_quote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.CharBlock()), ('source', wagtail.blocks.CharBlock())]))]),
        ),
    ]
