# Generated by Django 4.0.10 on 2023-05-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_alter_blogpage_body_alter_jobpage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpage',
            name='icon',
            field=models.CharField(choices=[('web/img/icons/phone.svg', 'phone'), ('web/img/icons/team.svg', 'team'), ('web/img/icons/email.svg', 'email'), ('web/img/icons/star.svg', 'star'), ('web/img/icons/crowd.svg', 'crowd'), ('web/img/icons/reports.svg', 'reports'), ('web/img/icons/wrench.svg', 'wrench'), ('web/img/icons/students.svg', 'students'), ('web/img/icons/dial.svg', 'dial'), ('web/img/icons/fast.svg', 'fast'), ('web/img/icons/love-hand.svg', 'love-hand'), ('web/img/icons/law.svg', 'law'), ('web/img/icons/tree.svg', 'tree'), ('web/img/icons/cash.svg', 'cash'), ('web/img/icons/valet.svg', 'valet'), ('web/img/icons/house.svg', 'house'), ('web/img/icons/universities.svg', 'universities'), ('web/img/icons/impact.svg', 'impact'), ('web/img/icons/clients.svg', 'clients'), ('web/img/icons/social', 'social'), ('web/img/icons/lawyer.svg', 'lawyer'), ('web/img/icons/partners.svg', 'partners'), ('web/img/icons/personal-growth.svg', 'personal-growth'), ('web/img/icons/change.svg', 'change'), ('web/img/icons/questionnaire.svg', 'questionnaire'), ('web/img/icons/document.svg', 'document'), ('web/img/icons/network.svg', 'network')], max_length=64),
        ),
    ]
