# Generated by Django 4.0.10 on 2023-11-19 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_alter_jobpage_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalnews',
            options={'verbose_name_plural': 'External News'},
        ),
    ]
