# Generated by Django 4.0.10 on 2024-01-02 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('web', '0022_alter_externalnews_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContentFeeback',
            new_name='ContentFeedback',
        ),
    ]
