# Generated by Django 4.0.10 on 2024-01-08 00:46

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0023_rename_contentfeeback_contentfeedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="full title")),
                    (
                        "paragraph",
                        wagtail.blocks.RichTextBlock(
                            features=["h3", "bold", "italic", "ol", "ul", "link"]
                        ),
                    ),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    ("quote", wagtail.blocks.BlockQuoteBlock()),
                ],
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="full title")),
                    (
                        "paragraph",
                        wagtail.blocks.RichTextBlock(
                            features=["h3", "bold", "italic", "ol", "ul", "link"]
                        ),
                    ),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                ],
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="newspage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="full title")),
                    (
                        "paragraph",
                        wagtail.blocks.RichTextBlock(
                            features=["h3", "bold", "italic", "ol", "ul", "link"]
                        ),
                    ),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    ("quote", wagtail.blocks.BlockQuoteBlock()),
                ],
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="resourcepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="full title")),
                    (
                        "paragraph",
                        wagtail.blocks.RichTextBlock(
                            features=["h3", "bold", "italic", "ol", "ul", "link"]
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="volunteerpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="full title")),
                    (
                        "paragraph",
                        wagtail.blocks.RichTextBlock(
                            features=["h3", "bold", "italic", "ol", "ul", "link"]
                        ),
                    ),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    ("quote", wagtail.blocks.BlockQuoteBlock()),
                    (
                        "attributed_quote",
                        wagtail.blocks.StructBlock(
                            [
                                ("quote", wagtail.blocks.CharBlock()),
                                ("source", wagtail.blocks.CharBlock()),
                            ]
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
