# Generated by Django 4.0.10 on 2024-01-08 04:24

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks

from wagtail.blocks.migrations.migrate_operation import MigrateStreamData
from wagtail.blocks.migrations.operations import StreamChildrenToStructBlockOperation


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0025_alter_blogpage_body_alter_jobpage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        form_classname="title", required=True
                                    ),
                                ),
                                (
                                    "size",
                                    wagtail.blocks.ChoiceBlock(
                                        blank=True,
                                        choices=[
                                            ("", "Select a header size"),
                                            ("h2", "H2"),
                                            ("h3", "H3"),
                                            ("h4", "H4"),
                                        ],
                                        required=False,
                                    ),
                                ),
                            ],
                            form_classname="full title",
                        ),
                    ),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    ("quote", wagtail.blocks.BlockQuoteBlock()),
                ],
                use_json_field=True,
            ),
        ),
    ]

"""
        MigrateStreamData(
            app_name="web",
            model_name="blogpage",
            field_name="body",
            operations_and_block_paths=[
                (
                    StreamChildrenToStructBlockOperation("heading", "text"),
                    "heading",
                ),
            ],
        ),
"""