# Generated by Django 4.2.16 on 2024-09-11 03:05

from django.db import migrations
from django.core import management


def _update_index(apps, schema_editor):
    management.call_command("wagtail_update_index")


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0026_wagtail_rebuild_references_index"),
    ]

    operations = [
        migrations.RunPython(_update_index, reverse_code=migrations.RunPython.noop)
    ]
