# Generated by Django 5.1.1 on 2025-05-05 04:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0026_delete_uploadedimage"),
        ("web", "0027_wagtail_search_update_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("subtitle", models.TextField(blank=True, max_length=512)),
                ("call_to_action_text", models.CharField(max_length=32)),
                ("call_to_action_url", models.URLField()),
                ("is_active", models.BooleanField(default=False)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Minimum image width is 800px. Landscape images are\n        preferable to portrait images. The ideal image ratio is 4:1, so the\n        image should be sized 800x200px or any multiple thereof.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
        ),
    ]
