# Generated by Django 5.1.1 on 2025-05-06 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("web", "0028_banner"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "donate_url",
                    models.URLField(
                        default="https://anika-legal.raisely.com/",
                        help_text="URL of donation website",
                        verbose_name="Donate URL",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Links",
            },
        ),
    ]
