# Generated by Django 5.1.1 on 2025-11-14 04:23

import django.db.models.deletion
import modelsearch.index
import taggit.managers
import wagtail.models.media
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("wagtailcore", "0095_groupsitepermission"),
        ("web", "0029_linksettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("file", models.FileField(upload_to="documents", verbose_name="file")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(editable=False, null=True),
                ),
                (
                    "file_hash",
                    models.CharField(blank=True, editable=False, max_length=40),
                ),
                (
                    "track_download",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to track downloads of this document.",
                        verbose_name="Track download?",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        default=wagtail.models.media.get_root_collection_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.collection",
                        verbose_name="collection",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text=None,
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="tags",
                    ),
                ),
                (
                    "uploaded_by_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uploaded by user",
                    ),
                ),
            ],
            options={
                "verbose_name": "document",
                "verbose_name_plural": "documents",
                "abstract": False,
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name="DocumentLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ACT", "Australian Capital Territory"),
                            ("NSW", "New South Wales"),
                            ("NT", "Northern Territory"),
                            ("QLD", "Queensland"),
                            ("SA", "South Australia"),
                            ("TAS", "Tasmania"),
                            ("VIC", "Victoria"),
                            ("WA", "Western Australia"),
                            ("ELSEWHERE", "I am from outside Australia"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("ACCESS_TO_JUSTICE", "Access to Justice"),
                            ("CLIMATE_RESILIENCE", "Climate Resilience"),
                            ("COMMUNITY_SERVICES", "Community Services"),
                            ("CONSUMER_PROTECTION", "Consumer Protection"),
                            ("DESIGN_AND_INNOVATION", "Design and Innovation"),
                            ("DISABILITY", "Disability"),
                            ("EDUCATION", "Education"),
                            ("FINANCIAL_COUNSELLING", "Financial Counselling"),
                            ("GOVERNMENT", "Government Departments and Agencies"),
                            ("HEALTH", "Health"),
                            ("HOUSING_SUPPORT_SERVICES", "Housing Support Services"),
                            ("MEDIA", "Media"),
                            ("PHILANTHROPY", "Philanthropy"),
                            ("POLICY_AND_RESEARCH", "Policy and Research"),
                            ("REAL_ESTATE_AND_PROPERTY", "Real Estate and Property"),
                            (
                                "REGULATION_AND_DISPUTE_RESOLUTION",
                                "Regulation and Dispute Resolution",
                            ),
                            ("RENTER", "Renter"),
                            ("OTHER", "Other"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "referrer",
                    models.CharField(
                        choices=[
                            ("NEWSLETTER", "Anika Newsletter"),
                            ("INTERNET_SEARCH", "Internet Search"),
                            ("NEWSPAPER", "Newspaper"),
                            ("PODCAST", "Podcast"),
                            ("RADIO", "Radio"),
                            ("SOCIAL_MEDIA", "Social Media"),
                            ("TELEVISION", "Television"),
                            ("WORD_OF_MOUTH", "Word of Mouth / Colleague"),
                            ("OTHER", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.customdocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "live",
                    models.BooleanField(
                        default=True, editable=False, verbose_name="live"
                    ),
                ),
                (
                    "has_unpublished_changes",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        verbose_name="has unpublished changes",
                    ),
                ),
                (
                    "first_published_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="first published at",
                    ),
                ),
                (
                    "last_published_at",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="last published at"
                    ),
                ),
                (
                    "go_live_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="go live date/time"
                    ),
                ),
                (
                    "expire_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expiry date/time"
                    ),
                ),
                (
                    "expired",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="expired"
                    ),
                ),
                ("title", models.CharField()),
                ("description", models.TextField(blank=True)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to feature this report prominently on the reports page. Only one report can be featured at a time.",
                    ),
                ),
                (
                    "accessible_document",
                    models.ForeignKey(
                        blank=True,
                        help_text="An accessible version of the report document (e.g., tagged PDF or Word document). Optional.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="web.customdocument",
                    ),
                ),
                (
                    "blog_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.blogpage",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.customdocument",
                    ),
                ),
                (
                    "latest_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="latest revision",
                    ),
                ),
                (
                    "live_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="live revision",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
