# Generated by Django 5.1.1 on 2025-11-10 03:26

import os

from django.core import management
from django.db import migrations


def _migrate_existing_documents(apps, schema_editor):
    if os.environ.get("PYTEST_CURRENT_TEST"):
        return

    Document = apps.get_model("wagtaildocs", "Document")
    CustomDocument = apps.get_model("web", "CustomDocument")

    # Migrate existing documents to CustomDocument
    for doc in Document.objects.all():
        CustomDocument.objects.create(
            title=doc.title,
            file=doc.file,
            file_size=doc.file_size,
            file_hash=doc.file_hash,
            uploaded_by_user=doc.uploaded_by_user,
        )

    # Rebuild the search index to include the new CustomDocument model.
    management.call_command("wagtail_update_index")


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0030_customdocument_documentlog_report"),
    ]

    operations = [
        migrations.RunPython(
            _migrate_existing_documents, reverse_code=migrations.RunPython.noop
        ),
    ]
