# Generated by Django 5.1.1 on 2025-11-19 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0032_populate_reports"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentlog",
            name="ip_address",
        ),
    ]
