# Generated by Django 5.1.1 on 2025-11-19 02:17

import django.db.models.deletion
from django.db import migrations, models


def _unpublish_banners(apps, schema_editor):
    """
    The new 'live' field is true by default but we don't want any banners to be
    live immediately after this migration is applied.
    """
    Banner = apps.get_model("web", "Banner")
    Banner.objects.filter(live=True).update(live=False)


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0095_groupsitepermission"),
        ("web", "0033_remove_documentlog_ip_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banner",
            name="is_active",
        ),
        migrations.AddField(
            model_name="banner",
            name="expire_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="expiry date/time"
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="expired",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="expired"
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="first_published_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="first published at"
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="go_live_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="go live date/time"
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="has_unpublished_changes",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="has unpublished changes"
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="last_published_at",
            field=models.DateTimeField(
                editable=False, null=True, verbose_name="last published at"
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="latest_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
                verbose_name="latest revision",
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="live",
            field=models.BooleanField(
                default=True, editable=False, verbose_name="live"
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="live_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
                verbose_name="live revision",
            ),
        ),
        migrations.RunPython(_unpublish_banners),
    ]
