# Generated by Django 5.1.1 on 2025-11-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0034_remove_banner_is_active_banner_expire_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="featured_text",
            field=models.TextField(
                blank=True,
                help_text='Optional text to use for the featured report link. Defaults to "Read our [report title] report" if left blank.',
            ),
        ),
    ]
