# Generated by Django 5.1.1 on 2025-11-26 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0027_image_description"),
        ("web", "0035_report_featured_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Images should ideally have a minimum width of 800px and a\n        ratio of approximately 4:1 (width:height) to display the entire image in\n        the available space. Landscape images are preferable to portrait\n        images. So an image with dimensions of 800x200px or any multiple\n        thereof is ideal.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
