# Generated by Django 5.1.1 on 2026-05-14 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0036_alter_banner_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="volunteerpage",
            name="main_image",
        ),
        migrations.RemoveField(
            model_name="volunteerpage",
            name="page_ptr",
        ),
        migrations.DeleteModel(
            name="VolunteerListPage",
        ),
        migrations.DeleteModel(
            name="VolunteerPage",
        ),
    ]
