# Generated by Django 5.1.1 on 2026-05-27 04:02

from django.db import migrations


SLUG_TAG_KEYWORDS = [
    ("evictions", ["evict"]),
    ("bonds", ["bond"]),
    ("repairs", ["repair"]),
]


def populate_blog_tags(apps, schema_editor):
    Tag = apps.get_model("taggit", "Tag")
    BlogPage = apps.get_model("web", "BlogPage")
    BlogPageTag = apps.get_model("web", "BlogPageTag")

    tag_slugs = {}
    for tag_slug, _ in SLUG_TAG_KEYWORDS:
        tag, _ = Tag.objects.get_or_create(
            slug=tag_slug,
            defaults={"name": tag_slug.capitalize()},
        )
        tag_slugs[tag_slug] = tag

    for page in BlogPage.objects.all():
        text = f"{page.slug} {(page.search_description or '').lower()}"
        for tag_slug, keywords in SLUG_TAG_KEYWORDS:
            if any(keyword in text for keyword in keywords):
                BlogPageTag.objects.get_or_create(
                    content_object_id=page.pk,
                    tag=tag_slugs[tag_slug],
                )

    # Explicitly add tags for some pages that don't have keywords in their slug or search description
    for page_slug, tag_slugs in [
        ("essential-homes", ["bonds", "evictions", "repairs"]),
        (
            "rental-legal-terms-made-simple-a-glossary-for-the-average-renter",
            ["bonds", "evictions", "repairs"],
        ),
    ]:
        page = BlogPage.objects.filter(slug=page_slug).first()
        if page:
            for tag_slug in tag_slugs:
                tag, _ = Tag.objects.get_or_create(
                    slug=tag_slug, defaults={"name": tag_slug.capitalize()}
                )
                BlogPageTag.objects.get_or_create(
                    content_object_id=page.pk,
                    tag=tag,
                )

    # Explicitly remove tags from some pages that have keywords in their slug or search description but aren't actually about those topics
    for page_slug, tag_slugs in [
        (
            "meet-sam-one-of-our-volunteer-paralegals",
            ["repairs"],
        ),
    ]:
        page = BlogPage.objects.filter(slug=page_slug).first()
        if page:
            for tag in tag_slugs:
                BlogPageTag.objects.filter(
                    content_object_id=page.pk,
                    tag__slug=tag,
                ).delete()


def remove_blog_tags(apps, schema_editor):
    Tag = apps.get_model("taggit", "Tag")
    BlogPageTag = apps.get_model("web", "BlogPageTag")

    for tag_slug, _ in SLUG_TAG_KEYWORDS:
        try:
            tag = Tag.objects.get(slug=tag_slug)
            BlogPageTag.objects.filter(tag=tag).delete()
        except Tag.DoesNotExist:
            pass


class Migration(migrations.Migration):
    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("web", "0038_blogpagetag_blogpage_tags"),
    ]

    operations = [
        migrations.RunPython(populate_blog_tags, reverse_code=remove_blog_tags),
    ]
