# Generated by Django 5.1.1 on 2026-05-29 00:29

import wagtail.admin.forms.choosers
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0039_populate_blog_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("paragraph", 1),
                    ("attributed_quote", 3),
                    ("accordion", 6),
                    ("link_button", 16),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "full title"},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.blocks.CharBlock", (), {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 2), ("source", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 2), ("content", 1)]],
                        {},
                    ),
                    5: ("wagtail.blocks.ListBlock", (4,), {}),
                    6: ("wagtail.blocks.StructBlock", [[("items", 5)]], {}),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("file", "File"),
                                ("custom_url", "Custom URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("phone", "Phone"),
                            ],
                            "classname": "link_choice_type_selector",
                            "label": "Link to",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "form_classname": "page_link",
                            "label": "Page",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "form_classname": "file_link",
                            "label": "File",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "custom_url_link url_field",
                            "label": "Custom URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [
                                wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()
                            ],
                        },
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "anchor_link",
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    12: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "phone_link",
                            "label": "Phone",
                            "max_length": 30,
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "form_classname": "new_window_toggle",
                            "label": "Open in new window",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 7),
                                ("page", 8),
                                ("file", 9),
                                ("custom_url", 10),
                                ("anchor", 11),
                                ("email", 12),
                                ("phone", 13),
                                ("new_window", 14),
                            ]
                        ],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 2), ("link", 15)]],
                        {},
                    ),
                },
            ),
        ),
    ]
