# Generated by Django 5.1.1 on 2026-05-29 00:55

import json

from django.db import migrations

#         "body": "[{\"id\": \"7c395d17-d549-4e94-8bfb-8a541ba9db7f\", \"type\": \"paragraph\", \"value\": \"<p data-block-key=\\\"fk7pv\\\">We support Victorian renters who might not be able to access traditional legal services.</p><p data-block-key=\\\"7bhfj\\\">You may be eligible if:</p><ul><li data-block-key=\\\"4749t\\\">You are a Victorian renter,</li><li data-block-key=\\\"eea2e\\\">On a low or middle income, and</li><li data-block-key=\\\"3b0ab\\\">You have a bonds, repairs, or evictions matter we can help with.</li></ul>\"}, {\"id\": \"90a7a144-88e8-47d0-bb2c-21f64d6046dd\", \"type\": \"link_button\", \"value\": {\"link\": {\"file\": null, \"page\": null, \"email\": \"\", \"phone\": \"\", \"anchor\": \"\", \"link_to\": \"custom_url\", \"custom_url\": \"https://intake.anikalegal.org.au\", \"new_window\": false}, \"text\": \"Get free help\"}}, {\"id\": \"07bc60f5-6f65-4aa7-b99b-25d2593fc856\", \"type\": \"accordion\", \"value\": {\"items\": [{\"id\": \"958aec0a-6848-4b43-926d-8bfe7d1dd9ac\", \"type\": \"item\", \"value\": {\"title\": \"What do you mean by Victorian renter?\", \"content\": \"<p data-block-key=\\\"0y4xs\\\">We can help if you have a problem in a residential tenancy based in Victoria. We can help both private and social housing renters.</p><p data-block-key=\\\"256lk\\\">Because the laws are different, we cannot help you if you aren\\u2019t in a residential tenancy. Some types of housing that we can\\u2019t assist with include rooming houses, caravan parks and retirement villages.</p><p data-block-key=\\\"4p1mu\\\">If you have a bonds problem, but you\\u2019ve since moved away from Victoria, we can still assist you!</p>\"}}, {\"id\": \"16d7f0b2-3a35-471e-90e1-145fcade6f66\", \"type\": \"item\", \"value\": {\"title\": \"What is a low or middle income?\", \"content\": \"<p data-block-key=\\\"7gft8\\\">We help renters who can\\u2019t afford legal help, and who are low to middle-income.</p><p data-block-key=\\\"5f7e7\\\">You don\\u2019t need to be on Centrelink to be eligible for our help. We look at your circumstances as a whole, including the proportion of your household income that goes to pay your rent, and how many dependents you have.</p><p data-block-key=\\\"20om1\\\">If you\\u2019re unsure if this is you, please submit an intake form and we will let you know!</p>\"}}, {\"id\": \"bcc05fb4-6dcf-4b9d-aa30-df459925e6fc\", \"type\": \"item\", \"value\": {\"title\": \"What types of bonds matters do you help with?\", \"content\": \"<p data-block-key=\\\"cml8s\\\">We can help you if your landlord has made a claim at VCAT or the Magistrates' Court to take some or all of your bond.</p><p data-block-key=\\\"2toh0\\\">Unfortunately, we can\\u2019t assist with disputes between co-renters. We have information about what happens when you move out, and someone takes over from you on our <a href=\\\"https://anikalegal.org.au/blog/what-happens-to-my-bond-if-im-moving-out-and-someone-is-taking-my-place/\\\">blog</a>.</p>\"}}, {\"id\": \"a01e1062-ceee-4c0c-b8f0-8934bbdadf86\", \"type\": \"item\", \"value\": {\"title\": \"What types of repairs problems can you help with?\", \"content\": \"<p data-block-key=\\\"cml8s\\\">Anika Legal can assist you to seek urgent and non-urgent repairs from your landlord.</p><p data-block-key=\\\"7apvk\\\">Unfortunately, we can\\u2019t assist with modifications or compensation claims. For assistance with these problems, we\\u2019d suggest contacting <a href=\\\"https://tenantsvic.org.au/\\\">Tenants Victoria</a>, or your local <a href=\\\"https://www.consumer.vic.gov.au/clubs-and-fundraising/funded-services-and-grants/tenancy-program-2021-26/tenancy-assistance-and-advocacy-program\\\">Tenancy Assistance and Advocacy Program.</a></p>\"}}, {\"id\": \"96ace242-3edf-4f1d-bca3-20b4a04b1ad3\", \"type\": \"item\", \"value\": {\"title\": \"What types of eviction matters can you help with?\", \"content\": \"<p data-block-key=\\\"cml8s\\\">Anika Legal can help you if you\\u2019ve received an eviction notice (called a notice to vacate), which you feel was in response to you exercising your rights as a renter. For example, if you request a repair and receive a notice to vacate not long after, we may be able to help.</p><p data-block-key=\\\"78e3m\\\">If your matter is very urgent, we may refer you to another service if we can\\u2019t help you in time. We cannot assist if a possession order has already been made.</p><p data-block-key=\\\"1ji35\\\">We cannot assist if you\\u2019ve received an eviction notice because you have not paid your rent. If you\\u2019ve fallen behind in your rent, there are other services you can contact, including:</p><ul><li data-block-key=\\\"5rgkp\\\"><a href=\\\"https://apps.justiceconnect.org.au/dear-landlord/\\\">Justice Connect\\u2019s Dear Landlord</a> to understand your options.</li><li data-block-key=\\\"bmik2\\\"><a href=\\\"https://www.anglicarevic.org.au/our-services/help-hub/rental-stress-program/\\\">Anglicare\\u2019s Rental Stress Program</a> for support from lawyers and financial counsellors.</li><li data-block-key=\\\"aeevk\\\">Your local <a href=\\\"https://www.consumer.vic.gov.au/clubs-and-fundraising/funded-services-and-grants/tenancy-program-2021-26/tenancy-assistance-and-advocacy-program\\\">Tenancy Assistance and Advocacy Program</a>.</li></ul>\"}}]}}]"


PAGE_BODY = [
    {
        "id": "7c395d17-d549-4e94-8bfb-8a541ba9db7f",
        "type": "paragraph",
        "value": '<p data-block-key="fk7pv">We support Victorian renters who might not be able to access traditional legal '
        'services.</p><p data-block-key="7bhfj">You may be eligible if:</p><ul><li data-block-key="4749t">You are a '
        'Victorian renter,</li><li data-block-key="eea2e">On a low or middle income, and</li><li '
        'data-block-key="3b0ab">You have a bonds, repairs, or evictions matter we can help with.</li></ul>',
    },
    {
        "id": "90a7a144-88e8-47d0-bb2c-21f64d6046dd",
        "type": "link_button",
        "value": {
            "link": {
                "anchor": "",
                "custom_url": "https://intake.anikalegal.org.au",
                "email": "",
                "file": None,
                "link_to": "custom_url",
                "new_window": False,
                "page": None,
                "phone": "",
            },
            "text": "Get free help",
        },
    },
    {
        "id": "07bc60f5-6f65-4aa7-b99b-25d2593fc856",
        "type": "accordion",
        "value": {
            "items": [
                {
                    "id": "958aec0a-6848-4b43-926d-8bfe7d1dd9ac",
                    "type": "item",
                    "value": {
                        "content": '<p data-block-key="0y4xs">We can help if you have a problem in a '
                        "residential tenancy based in Victoria. We can help both private and "
                        'social housing renters.</p><p data-block-key="256lk">Because the laws are '
                        "different, we cannot help you if you aren't in a residential tenancy. "
                        "Some types of housing that we can't assist with include rooming houses, "
                        'caravan parks and retirement villages.</p><p data-block-key="4p1mu">If '
                        "you have a bonds problem, but you've since moved away from Victoria, we "
                        "can still assist you!</p>",
                        "title": "What do you mean by Victorian renter?",
                    },
                },
                {
                    "id": "16d7f0b2-3a35-471e-90e1-145fcade6f66",
                    "type": "item",
                    "value": {
                        "content": '<p data-block-key="7gft8">We help renters who can\'t afford legal help, '
                        'and who are low to middle-income.</p><p data-block-key="5f7e7">You don\'t '
                        "need to be on Centrelink to be eligible for our help. We look at your "
                        "circumstances as a whole, including the proportion of your household "
                        "income that goes to pay your rent, and how many dependents you "
                        'have.</p><p data-block-key="20om1">If you\'re unsure if this is you, '
                        "please submit an intake form and we will let you know!</p>",
                        "title": "What is a low or middle income?",
                    },
                },
                {
                    "id": "bcc05fb4-6dcf-4b9d-aa30-df459925e6fc",
                    "type": "item",
                    "value": {
                        "content": '<p data-block-key="cml8s">We can help you if your landlord has made a '
                        "claim at VCAT or the Magistrates' Court to take some or all of your "
                        'bond.</p><p data-block-key="2toh0">Unfortunately, we can\'t assist with '
                        "disputes between co-renters. We have information about what happens when "
                        "you move out, and someone takes over from you on our <a "
                        'href="https://anikalegal.org.au/blog/what-happens-to-my-bond-if-im-moving-out-and-someone-is-taking-my-place/">blog</a>.</p>',
                        "title": "What types of bonds matters do you help with?",
                    },
                },
                {
                    "id": "a01e1062-ceee-4c0c-b8f0-8934bbdadf86",
                    "type": "item",
                    "value": {
                        "content": '<p data-block-key="cml8s">Anika Legal can assist you to seek urgent and '
                        "non-urgent repairs from your landlord.</p><p "
                        'data-block-key="7apvk">Unfortunately, we can\'t assist with modifications '
                        "or compensation claims. For assistance with these problems, we'd suggest "
                        'contacting <a href="https://tenantsvic.org.au/">Tenants Victoria</a>, or '
                        "your local <a "
                        'href="https://www.consumer.vic.gov.au/clubs-and-fundraising/funded-services-and-grants/tenancy-program-2021-26/tenancy-assistance-and-advocacy-program">Tenancy '
                        "Assistance and Advocacy Program.</a></p>",
                        "title": "What types of repairs problems can you help with?",
                    },
                },
                {
                    "id": "96ace242-3edf-4f1d-bca3-20b4a04b1ad3",
                    "type": "item",
                    "value": {
                        "content": '<p data-block-key="cml8s">Anika Legal can help you if you\'ve received an '
                        "eviction notice (called a notice to vacate), which you feel was in "
                        "response to you exercising your rights as a renter. For example, if you "
                        "request a repair and receive a notice to vacate not long after, we may be "
                        'able to help.</p><p data-block-key="78e3m">If your matter is very urgent, '
                        "we may refer you to another service if we can't help you in time. We "
                        "cannot assist if a possession order has already been made.</p><p "
                        'data-block-key="1ji35">We cannot assist if you\'ve received an eviction '
                        "notice because you have not paid your rent. If you've fallen behind in "
                        "your rent, there are other services you can contact, "
                        'including:</p><ul><li data-block-key="5rgkp"><a '
                        'href="https://apps.justiceconnect.org.au/dear-landlord/">Justice '
                        "Connect's Dear Landlord</a> to understand your options.</li><li "
                        'data-block-key="bmik2"><a '
                        'href="https://www.anglicarevic.org.au/our-services/help-hub/rental-stress-program/">Anglicare\'s '
                        "Rental Stress Program</a> for support from lawyers and financial "
                        'counsellors.</li><li data-block-key="aeevk">Your local <a '
                        'href="https://www.consumer.vic.gov.au/clubs-and-fundraising/funded-services-and-grants/tenancy-program-2021-26/tenancy-assistance-and-advocacy-program">Tenancy '
                        "Assistance and Advocacy Program</a>.</li></ul>",
                        "title": "What types of eviction matters can you help with?",
                    },
                },
            ]
        },
    },
]


def update_resource_page(apps, schema_editor):
    ResourcePage = apps.get_model("web", "ResourcePage")
    page = ResourcePage.objects.filter(slug="eligibility-criteria").first()
    if page:
        page.body = json.dumps(PAGE_BODY)
        page.save()


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0040_alter_resourcepage_body"),
    ]

    operations = [
        migrations.RunPython(
            update_resource_page, reverse_code=migrations.RunPython.noop
        ),
    ]
