version: "3"

services:
  # Local development database.
  database:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 25432:5432

  # Django webserver.
  web:
    command: make web-local
    image: clerk:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    links:
      - database
    environment:
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: password
      PGHOST: database
      PGPORT: 5432
      DJANGO_SETTINGS_MODULE: clerk.settings.dev
      # Read from .env
      SENDGRID_API_KEY: $SENDGRID_API_KEY
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

  # For testing.
  test:
    image: clerk:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    links:
      - database
    environment:
      PGUSER: postgres
      PGPASSWORD: password
      PGHOST: database
      PGPORT: 5432
      DJANGO_SETTINGS_MODULE: clerk.settings.test

volumes:
  postgres-data:
