version: '3'

services:
    # Local development database.
    database:
        image: postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - 25432:5432

    # Django webserver.
    web:
        image: localhost:5000/clerk
        command: make web-local
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        volumes:
          - ./app:/app
          - build:/app/build
          - node_modules:/app/node_modules
        links:
            - database
            - webpack
        environment:
            PGDATABASE: postgres
            PGUSER: postgres
            PGPASSWORD: password
            PGHOST: database
            PGPORT: 5432
            DJANGO_SETTINGS_MODULE: clerk.settings.dev

    # Webpack build for frontend assets.
    webpack:
        image: localhost:5000/clerk
        command: make webpack
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./app:/app
            - node_modules:/app/node_modules
            - build:/app/build

volumes:
    postgres-data:
    node_modules:
    build:
