# PostgreSQL Client Authentication Configuration File
# ===================================================
# TYPE  DATABASE        USER            ADDRESS                 METHOD
host    all             all             35.90.103.132/30        scram-sha-256
host    all             all             44.208.168.68/30        scram-sha-256