# Generated by Django 4.0.10 on 2024-04-24 02:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0071_alter_issueevent_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "modified_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("ANY", "Any"),
                            ("REPAIRS", "Repairs"),
                            ("BONDS", "Bonds"),
                            ("EVICTION", "Eviction"),
                            ("HEALTH_CHECK", "Housing Health Check"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("CREATE", "Created"),
                            ("LAWYER", "Lawyer assigned"),
                            ("PARALEGAL", "Paralegal assigned"),
                            ("STAGE", "Stage change"),
                            ("OPEN", "Open change"),
                        ],
                        default="STAGE",
                        max_length=32,
                    ),
                ),
                (
                    "event_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UNSTARTED", "Not started"),
                            ("CLIENT_AGREEMENT", "Client agreement"),
                            ("ADVICE", "Drafting advice"),
                            ("FORMAL_LETTER", "Formal letter sent"),
                            ("NEGOTIATIONS", "Negotiations"),
                            ("VCAT_CAV", "VCAT/CAV"),
                            ("POST_CASE_INTERVIEW", "Post-case interview"),
                            ("CLOSED", "Closed"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "tasks_assigned_to",
                    models.CharField(
                        choices=[
                            ("PARALEGAL", "The paralegal assigned to the case"),
                            ("LAWYER", "The lawyer assigned to the case"),
                            ("COORDINATOR", "Coordinators"),
                        ],
                        max_length=32,
                    ),
                ),
            ],
            options={
                "verbose_name": "trigger",
            },
        ),
        migrations.CreateModel(
            name="TaskTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "modified_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "trigger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        related_query_name="template",
                        to="task.tasktrigger",
                    ),
                ),
            ],
            options={
                "verbose_name": "template",
                "order_with_respect_to": "trigger",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "modified_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not started"),
                            ("IN_PROGRESS", "In progress"),
                            ("DONE", "Done"),
                            ("NOT_DONE", "Not done"),
                        ],
                        default="NOT_STARTED",
                        max_length=32,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.issue"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="task.tasktemplate",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
