# Generated by Django 5.1.1 on 2025-07-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasktrigger",
            name="topic",
            field=models.CharField(
                choices=[
                    ("ANY", "Any"),
                    ("REPAIRS", "Repairs"),
                    ("BONDS", "Bonds"),
                    ("EVICTION_ARREARS", "Eviction (Arrears)"),
                    ("EVICTION_RETALIATORY", "Eviction (Retaliatory)"),
                    ("HEALTH_CHECK", "Housing Health Check"),
                ],
                max_length=32,
            ),
        ),
    ]
