# Generated by Django 3.0.8 on 2020-07-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_jotformsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='webflowcontact',
            name='referral',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
