# Generated by Django 3.1 on 2020-09-19 00:29

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0004_webflowcontact_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jotformsubmission',
            name='answers',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
