# Generated by Django 3.1.3 on 2020-12-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0005_auto_20200919_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='webflowcontact',
            name='number_callbacks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webflowcontact',
            name='requires_callback',
            field=models.BooleanField(default=True),
        ),
    ]
