# Generated by Django 3.1.3 on 2020-12-20 05:18

from django.db import migrations


def update_entries(apps, schema_editor):
    """
    Update historical WebflowContact entries so that requires_callback field is false
    """
    Contact = apps.get_model("webhooks", "WebflowContact")

    for contact in Contact.objects.all():
        contact.requires_callback = False
        contact.save()


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0006_auto_20201220_1614"),
    ]

    operations = [migrations.RunPython(update_entries)]

