# Generated by Django 4.0.4 on 2022-05-31 04:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0008_webflowcontact_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('topic', models.CharField(choices=[('REPAIRS', 'Repairs'), ('BONDS', 'Bonds'), ('RENT_REDUCTION', 'Rent reduction'), ('EVICTION', 'Eviction'), ('OTHER', 'Other')], max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
