# Generated by Django 4.0.4 on 2022-07-14 01:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0009_noemailsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noemailsubmission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
