# Generated by Django 4.0.10 on 2023-05-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0010_alter_closedcontact_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedcontact',
            name='topic',
            field=models.CharField(choices=[('REPAIRS', 'Repairs'), ('BONDS', 'Bonds'), ('EVICTION', 'Eviction'), ('HEALTH_CHECK', 'Housing Health Check'), ('RENT_REDUCTION', 'Rent reduction'), ('OTHER', 'Other')], max_length=32),
        ),
    ]
