# Generated by Django 4.0.10 on 2024-01-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0011_alter_closedcontact_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webflowcontact',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
