# Generated by Django 5.1.1 on 2026-07-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0014_alter_closedcontact_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webflowcontact",
            name="email",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
