openapi: 3.0.1
info:
  title: Clerk API
  description: API that the Django backend will provide.
  version: 0.1.0

paths:
  /clerk/api/case/:
    $ref: paths/case-list.yaml
  /clerk/api/case/{id}/:
    $ref: paths/case-detail.yaml
  /clerk/api/case/{id}/note/:
    $ref: paths/case-note.yaml
  /clerk/api/case/{id}/docs/:
    $ref: paths/case-docs.yaml
  /clerk/api/email/{id}/:
    $ref: paths/email-list.yaml
  /clerk/api/email/{id}/{emailId}/:
    $ref: paths/email-detail.yaml
  /clerk/api/email/{id}/{emailId}/attachment/:
    $ref: paths/attachment-list.yaml
  /clerk/api/email/{id}/{emailId}/attachment/{attachmentId}/:
    $ref: paths/attachment-detail.yaml
  /clerk/api/email/{id}/{emailId}/attachment/{attachmentId}/sharepoint/:
    $ref: paths/attachment-sharepoint-upload.yaml
  /clerk/api/email/{id}/{emailId}/attachment/{attachmentId}/sharepoint/{sharepointId}/:
    $ref: paths/attachment-sharepoint-download.yaml
  /clerk/api/person/:
    $ref: paths/person-list.yaml
  /clerk/api/person/search/:
    $ref: paths/person-search.yaml
  /clerk/api/person/{id}/:
    $ref: paths/person-detail.yaml
  /clerk/api/tenancy/{id}/:
    $ref: paths/tenancy-detail.yaml
  /clerk/api/client/{id}/:
    $ref: paths/client-detail.yaml
  /clerk/api/account/:
    $ref: paths/account-list.yaml
  /clerk/api/account/{id}/:
    $ref: paths/account-detail.yaml
  /clerk/api/account/{id}/perms/:
    $ref: paths/account-perms.yaml
  /clerk/api/account/{id}/perms-resync/:
    $ref: paths/account-perms-resync.yaml
  /clerk/api/account/{id}/perms-promote/:
    $ref: paths/account-perms-promote.yaml
  /clerk/api/account/{id}/perms-demote/:
    $ref: paths/account-perms-demote.yaml
  /clerk/api/template-email/:
    $ref: paths/template-email-list.yaml
  /clerk/api/template-email/{id}/:
    $ref: paths/template-email-detail.yaml
  /clerk/api/template-notify/:
    $ref: paths/template-notify-list.yaml
  /clerk/api/template-notify/{id}/:
    $ref: paths/template-notify-detail.yaml
  /clerk/api/template-doc/:
    $ref: paths/template-doc-list.yaml
  /clerk/api/template-doc/{id}/:
    $ref: paths/template-doc-detail.yaml
