# Generated by Django 3.0.5 on 2020-04-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0005_submission_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="num_answers",
            field=models.IntegerField(default=0),
        ),
    ]
