# Generated by Django 3.0.8 on 2020-07-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_submission_is_case_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
