# Generated by Django 3.1 on 2020-09-13 05:04

from django.db import migrations


def migrate_questions_to_other_apps(apps, schema_editor):
    """
    Move all questions data into core and tenancy apps
    """
    # Old models
    SubmissionOld = apps.get_model("questions", "Submission")
    FileUploadOld = apps.get_model("questions", "FileUpload")
    ImageUploadOld = apps.get_model("questions", "ImageUpload")
    # New models!
    Submission = apps.get_model("core", "Submission")
    Client = apps.get_model("core", "Client")
    Person = apps.get_model("core", "Person")
    FileUpload = apps.get_model("core", "FileUpload")
    Tenancy = apps.get_model("tenancy", "Tenancy")


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0010_submission_is_reminder_sent"),
        ("core", "0001_initial"),
        ("tenancy", "0001_initial"),
    ]

    operations = [migrations.RunPython(migrate_questions_to_other_apps)]
