#
# CircleCI Build Script
#
# TODO (build, test, deploy)
#   - python unit tests
#   - JS unit tests
# ALSO NICE TOOD:
#   - scheduled build of base image
#   - run ansible / CF to spin up environment
#   - schedule DB backups
#
version: 2
jobs:
  build:
    working_directory: ~/repo
    machine: true
    steps:
      # Clone code from GitHub
      - checkout

      # Generate the project checksum
      - run: ./scripts/build/checksum.sh

      # Try pull the docker image from cache (~20s) or
      - restore_cache:
          keys:
            - clerk-image-v1-{{ checksum ".checksum" }}

      # Build the clerk Docker image (~1 minute)
      # then save it so we can share it between jobs (~15s)
      # unless there is a cached image already, in which case we skip this step.
      - run: ./scripts/build/build_image_if_required.sh

      # Save our image to the CircleCI job cache (~45s)
      - save_cache:
          paths:
            - image.tar
          key: clerk-image-v1-{{ checksum ".checksum" }}

  lint:
    working_directory: ~/repo
    machine: true
    steps:
      # Clone code from GitHub
      - checkout

      # Generate the project checksum
      - run: ./scripts/build/checksum.sh

      # Pull docker image from cache (~20s)
      - restore_cache:
          keys:
            - clerk-image-v1-{{ checksum ".checksum" }}

      # Load our docker image from the .tar file (~30s)
      - run: docker load -i image.tar

      # Run code linting (<1s)
      - run: docker run anikalaw/clerk make lint

  push:
    working_directory: ~/repo
    machine: true
    steps:
      # Clone code from GitHub
      - checkout

      # Generate the project checksum
      - run: ./scripts/build/checksum.sh

      # Pull docker image from cache (~20s)
      - restore_cache:
          keys:
            - clerk-image-v1-{{ checksum ".checksum" }}

      # Load our docker image from the .tar file (~30s)
      - run: docker load -i image.tar

      # Login to Docker Hub
      - run: docker login --username $DOCKER_ID --password $DOCKER_PASSWORD

      # Push docker image to Docker Hub (~50s)
      - run: docker push anikalaw/clerk

  deploy:
    working_directory: ~/repo
    machine: true
    steps:
      # Clone code from GitHub
      - checkout

      # Deploy built container to Docker Swarm on webserver
      - run: ./scripts/deploy/deploy.sh

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - lint:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - lint
      - push:
          requires:
            - hold
      - deploy:
          requires:
            - push
