allOf:
  - $ref: ./ServiceBase.yaml
  - type: object
    properties:
      id:
        type: integer
      issue_id:
        type: string
        format: uuid
    required:
      - id
      - issue_id
