# Generated by Django 5.1.1 on 2024-09-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blacklist", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="blacklist",
            name="blacklist_blacklist_email_and_phone_not_null",
        ),
        migrations.AddConstraint(
            model_name="blacklist",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("email__isnull", True), ("phone__isnull", True), _negated=True
                ),
                name="blacklist_blacklist_email_and_phone_not_null",
                violation_error_message="An email or phone number must be provided",
            ),
        ),
    ]
