FROM node:latest

WORKDIR /frontend

# Install Node modules, build frontend for prod.
COPY frontend/package.json .
COPY frontend/package-lock.json .
RUN echo "Installing Node modules." && \
    npm install --silent

# Mount the codebase
ADD frontend /frontend

RUN echo "Building frontend" && \ 
    npm run build