version: "3"

services:
  web:
    command: make web-prod
    image: anikalaw/clerk:latest
    ports:
      - 8000:8000
    volumes:
      - /var/run/postgresql:/app/postgres.sock
      - /var/log/clerk/prod/web:/var/log
    environment:
      DJANGO_SETTINGS_MODULE: clerk.settings.prod
      GUNICORN_PORT: 8000
      PGHOST: /app/postgres.sock
      PGPORT: 5432
      PGDATABASE: clerk
      PGUSER: $PGUSER
      PGPASSWORD: $PGPASSWORD
      # Pass through
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      SENDGRID_API_KEY: $SENDGRID_API_KEY
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      RAVEN_DSN: $RAVEN_DSN

  worker:
    command: make worker-prod
    image: anikalaw/clerk:latest
    volumes:
      - /var/run/postgresql:/app/postgres.sock
      - /var/log/clerk/prod/worker:/var/log
    environment:
      DJANGO_SETTINGS_MODULE: clerk.settings.prod
      PGHOST: /app/postgres.sock
      PGPORT: 5432
      PGDATABASE: clerk
      PGUSER: $PGUSER
      PGPASSWORD: $PGPASSWORD
      # Pass through
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      SENDGRID_API_KEY: $SENDGRID_API_KEY
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      RAVEN_DSN: $RAVEN_DSN
