services:
  # Local development database.
  clerk_db:
    container_name: clerk_db
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - clerk-postgres-data:/var/lib/postgresql/data
    ports:
      - 25432:5432
  # Django webserver.
  web:
    command: bash /app/scripts/web/local.sh
    image: clerk:local
    ports:
      - 8000:8000
      - 8123:8123 # Debug
    volumes:
      - ../app:/app
      - /app/.venv/ # Exclude
      - config_local:/root/.config
    links:
      - worker
      - frontend
      - clerk_db
    env_file:
      - ../env/dev.env
    environment:
      - SHELLOPTS=vi
      - HISTFILE=/root/.config/bash_history
      - IPYTHON_DIR=/root/.config/ipython
  # Django-q worker.
  worker:
    command: bash /app/scripts/worker/local.sh
    image: clerk:local
    volumes:
      - ../app:/app
      - /app/.venv/ # Exclude
    links:
      - clerk_db
    env_file:
      - ../env/dev.env
  frontend:
    image: clerk-frontend:local
    command: npm run dev
    ports:
      - 5173:5173
    volumes:
      - ../frontend/src:/frontend/src
      - ../frontend/vite.config.ts:/frontend/vite.config.ts
      - ../frontend/package.json:/frontend/package.json
  # For testing.
  test:
    image: clerk:local
    volumes:
      - ../app:/app
      - /app/.venv/ # Exclude
    links:
      - clerk_db
    env_file:
      - ../env/test.env
volumes:
  clerk-postgres-data:
  config_local: