version: "3"

services:
  web:
    command: bash /app/scripts/web/prod.sh
    image: anikalaw/clerk:staging
    ports:
      - 8001:8001
    volumes:
      - /var/run/postgresql:/app/postgres.sock
      - /var/log/clerk/test/web:/var/log
    env_file:
      - staging.env

  worker:
    command: bash /app/scripts/worker/prod.sh
    image: anikalaw/clerk:staging
    volumes:
      - /var/run/postgresql:/app/postgres.sock
      - /var/log/clerk/test/worker:/var/log
    env_file:
      - staging.env

  # Server-side rendering of React pages.
  ssr:
    image: anikalaw/clerk-webpack:staging
    command: npm run ssr
    ports:
      - 3002:3002
    environment:
      EXPRESS_PORT: 3002
