version: "3"

services:
  # Local development database.
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - clerk-postgres-data:/var/lib/postgresql/data
    ports:
      - 25432:5432

  # Django webserver.
  web:
    command: bash /app/scripts/web/local.sh
    image: clerk:local
    ports:
      - 8000:8000
    volumes:
      - ../app:/app
      - build:/build
    links:
      - db
      - worker
      - webpack
      - ssr
    env_file:
      - ../env/dev.env

  # Django-q worker.
  worker:
    command: bash /app/scripts/worker/local.sh
    image: clerk:local
    volumes:
      - ../app:/app
    links:
      - db
    env_file:
      - ../env/dev.env

  # Server-side rendering of React pages.
  ssr:
    image: clerk-webpack:local
    command: npm run ssr
    ports:
      - 3002:3002
    environment:
      EXPRESS_PORT: 3002
    volumes:
      - ../frontend/package.json:/frontend/package.json
      - ../frontend/node_modules:/frontend/node_modules
      - build:/build

  # Webpack build server
  webpack:
    image: clerk-webpack:local
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ../frontend/src:/frontend/src
      - ../frontend/webpack.config.js:/frontend/webpack.config.js
      - ../frontend/babel.config.js:/frontend/babel.config.js
      - ../frontend/package.json:/frontend/package.json
      - ../frontend/node_modules:/frontend/node_modules
      - build:/build

  # For testing.
  test:
    image: clerk:local
    volumes:
      - ../app:/app
    links:
      - db
    env_file:
      - ../env/test.env

volumes:
  clerk-postgres-data:
  build:
