version: "3"

services:
  # Django webserver.
  web:
    command: bash /app/scripts/web/prod.sh
    image: anikalaw/clerk:prod
    ports:
      - 8000:8000
    volumes:
      - /var/run/postgresql:/app/postgres.sock
      - /var/log/clerk/prod/web:/var/log
    env_file:
      - prod.env

  # Django-q worker.
  worker:
    command: bash /app/scripts/worker/prod.sh
    image: anikalaw/clerk:prod
    volumes:
      - /var/run/postgresql:/app/postgres.sock
      - /var/log/clerk/prod/worker:/var/log
    env_file:
      - prod.env

  # Server-side rendering of React pages.
  ssr:
    image: anikalaw/clerk-webpack:prod
    command: npm run ssr
    ports:
      - 3002:3002
    environment:
      EXPRESS_PORT: 3002
