version: "3"

services:
  # Local development database.
  clerk_db:
    container_name: clerk_db
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - clerk-postgres-data:/var/lib/postgresql/data
    ports:
      - 25432:5432

  # Django webserver.
  web:
    container_name: web
    command: bash /app/scripts/web/local.sh
    image: clerk:local
    ports:
      - 8000:8000
    volumes:
      - ../app:/app
    links:
      - worker
      - clerk_db
    env_file:
      - ../env/dev.env

  # Django-q worker.
  worker:
    container_name: worker
    command: bash /app/scripts/worker/local.sh
    image: clerk:local
    volumes:
      - ../app:/app
    links:
      - clerk_db
    env_file:
      - ../env/dev.env

  # For testing.
  test:
    container_name: test
    image: clerk:local
    volumes:
      - ../app:/app
    links:
      - clerk_db
    env_file:
      - ../env/test.env

volumes:
  clerk-postgres-data:
