version: "3"

services:
  web:
    command: bash /app/scripts/web/prod.sh
    image: anikalaw/clerk:prod
    ports:
      - 8000:8000
    volumes:
      - /var/run/postgresql:/app/postgres.sock
      - /var/log/clerk/prod/web:/var/log
    env_file:
      - prod.env

  worker:
    command: bash /app/scripts/worker/prod.sh
    image: anikalaw/clerk:prod
    volumes:
      - /var/run/postgresql:/app/postgres.sock
      - /var/log/clerk/prod/worker:/var/log
    env_file:
      - prod.env
