FROM node:23.1.0

WORKDIR /frontend

# Install Node modules, build Webpack for prod.
COPY frontend/package.json .
COPY frontend/package-lock.json .
RUN echo "Installing Node modules." && \
    npm install --silent

# Mount the codebase
ADD frontend /frontend

# Build webpack from production
RUN echo "Building Webpack." && \ 
    npm run build
