version: "3"

services:
  # Local development database.
  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 25432:5432

  # Django webserver.
  web:
    container_name: web
    command: make web-local
    image: clerk:latest
    ports:
      - 8000:8000
    volumes:
      - ../app:/app
    links:
      - streamlit
      - worker
      - database
    environment:
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: password
      PGHOST: database
      PGPORT: 5432
      DJANGO_SETTINGS_MODULE: clerk.settings.dev
      # Read from .env
      SENDGRID_API_KEY: $SENDGRID_API_KEY
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

  # Reporting server.
  streamlit:
    container_name: streamlit
    command: streamlit hello --browser.serverAddress localhost
    image: clerk:latest
    ports:
      - 8501:8501
    volumes:
      - ../app:/app
    links:
      - database
    environment:
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: password
      PGHOST: database
      PGPORT: 5432

  # Django-q worker.
  worker:
    container_name: worker
    command: make worker-local
    image: clerk:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../app:/app
    links:
      - database
    environment:
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: password
      PGHOST: database
      PGPORT: 5432
      DJANGO_SETTINGS_MODULE: clerk.settings.dev
      # Read from .env
      SENDGRID_API_KEY: $SENDGRID_API_KEY
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

  # For testing.
  test:
    container_name: test
    image: clerk:latest
    volumes:
      - ../app:/app
    links:
      - database
    environment:
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: password
      PGHOST: database
      PGPORT: 5432
      DJANGO_SETTINGS_MODULE: clerk.settings.test

volumes:
  postgres-data:
