version: "3"

services:
  # Local development database.
  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - clerk-postgres-data:/var/lib/postgresql/data
    ports:
      - 25432:5432

  # Django webserver.
  web:
    container_name: web
    command: bash /app/scripts/web/local.sh
    image: clerk:local
    ports:
      - 8000:8000
    volumes:
      - ../app:/app
    links:
      - worker
      - database
    environment:
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: password
      PGHOST: database
      PGPORT: 5432
      DJANGO_SETTINGS_MODULE: clerk.settings.dev
      # Read from .env
      SENDGRID_API_KEY: $SENDGRID_API_KEY
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      ACTIONSTEP_CLIENT_ID: $ACTIONSTEP_CLIENT_ID
      ACTIONSTEP_CLIENT_SECRET: $ACTIONSTEP_CLIENT_SECRET
      MAILCHIMP_API_KEY: $MAILCHIMP_API_KEY
      TWILIO_ACCOUNT_SID: $TWILIO_ACCOUNT_SID
      TWILIO_AUTH_TOKEN: $TWILIO_AUTH_TOKEN
      GOOGLE_OAUTH2_KEY: $GOOGLE_OAUTH2_KEY
      GOOGLE_OAUTH2_SECRET: $GOOGLE_OAUTH2_SECRET
      AZURE_AD_CLIENT_ID: $AZURE_AD_CLIENT_ID
      AZURE_AD_CLIENT_SECRET: $AZURE_AD_CLIENT_SECRET

  # Django-q worker.
  worker:
    container_name: worker
    command: bash /app/scripts/worker/local.sh
    image: clerk:local
    volumes:
      - ../app:/app
    links:
      - database
    environment:
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: password
      PGHOST: database
      PGPORT: 5432
      DJANGO_SETTINGS_MODULE: clerk.settings.dev
      # Read from .env
      SENDGRID_API_KEY: $SENDGRID_API_KEY
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      ACTIONSTEP_CLIENT_ID: $ACTIONSTEP_CLIENT_ID
      ACTIONSTEP_CLIENT_SECRET: $ACTIONSTEP_CLIENT_SECRET
      MAILCHIMP_API_KEY: $MAILCHIMP_API_KEY
      TWILIO_ACCOUNT_SID: $TWILIO_ACCOUNT_SID
      TWILIO_AUTH_TOKEN: $TWILIO_AUTH_TOKEN
      AZURE_AD_CLIENT_ID: $AZURE_AD_CLIENT_ID
      AZURE_AD_CLIENT_SECRET: $AZURE_AD_CLIENT_SECRET
      SLACK_API_TOKEN: $SLACK_API_TOKEN

  # For testing.
  test:
    container_name: test
    image: clerk:local
    volumes:
      - ../app:/app
    links:
      - database
    environment:
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: password
      PGHOST: database
      PGPORT: 5432
      DJANGO_SETTINGS_MODULE: clerk.settings.test
      ACTIONSTEP_CLIENT_ID: ""
      ACTIONSTEP_CLIENT_SECRET: ""
      MAILCHIMP_API_KEY: ""
      TWILIO_ACCOUNT_SID: ""
      TWILIO_AUTH_TOKEN: ""
      AZURE_AD_CLIENT_ID: ""
      AZURE_AD_CLIENT_SECRET: ""

volumes:
  clerk-postgres-data:
