import logging

import time
from playwright import sync_playwright

logging.basicConfig(level=logging.INFO)
log = logging.getLogger(__name__)

def run(playwright):
    browser = playwright.chromium.launch(headless=True)
    context = browser.newContext()
    page = context.newPage()
    log.info("Loading staging intake form.")
    page.goto("https://test-intake.anikalegal.com/")
    page.click("text=\"Let’s get started\"")
    page.click("text=\"Thank you\"")

    log.info("Filling out client info.")
    page.click("input[placeholder=\"Type your answer here...\"]")
    page.fill("input[placeholder=\"Type your answer here...\"]", "Matt")
    page.click("text=\"OK\"")
    page.click("input[placeholder=\"Type your answer here...\"]")
    page.fill("input[placeholder=\"Type your answer here...\"]", "Segal")
    page.click("text=\"OK\"")
    page.click("input[placeholder=\"Type your answer here...\"]")
    page.fill("input[placeholder=\"Type your answer here...\"]", "matt@gmail.com")
    page.click("//button[normalize-space(.)='OK']/span")

    log.info("Filling out eligibility info.")
    page.click("text=/.*Yes.*/")
    time.sleep(1)
    page.click("text=/.*Yes.*/")
    time.sleep(1)

    log.info("Filling out tenancy info.")
    page.click("text=/.*I need rental repairs.*/")
    page.click("text=/.*I need a reduction in rent.*/")
    page.click("text=/.*I need a reduction in rent.*/")
    page.click("text=\"OK\"")
    page.click("input[placeholder=\"Type your answer here...\"]")
    page.fill("input[placeholder=\"Type your answer here...\"]", "123 Fake St")
    page.click("text=\"OK\"")
    page.click("input[placeholder=\"DD\"]")
    page.fill("input[placeholder=\"DD\"]", "1")
    page.press("input[placeholder=\"DD\"]", "Tab")
    page.fill("input[placeholder=\"MM\"]", "1")
    page.press("input[placeholder=\"MM\"]", "Tab")
    page.fill("input[placeholder=\"YYYY\"]", "1990")
    page.click("//button[normalize-space(.)='OK']/span/*[local-name()=\"svg\"]")
    page.click("text=/.*Yes.*/")
    page.click("text=\"Continue\"")

    log.info("Filling out repairs info.")
    page.click("//div[normalize-space(.)='AWater']")
    page.click("text=\"OK\"")
    page.click("input[placeholder=\"Type your answer here...\"]")
    page.fill("input[placeholder=\"Type your answer here...\"]", "Water is broken")
    page.click("text=\"OK\"")
    page.click("input[placeholder=\"DD\"]")
    page.fill("input[placeholder=\"DD\"]", "1")
    page.press("input[placeholder=\"DD\"]", "Tab")
    page.fill("input[placeholder=\"MM\"]", "1")
    page.press("input[placeholder=\"MM\"]", "Tab")
    page.fill("input[placeholder=\"YYYY\"]", "1990")
    page.click("text=\"OK\"")
    page.click("text=\"Skip\"")
    page.click("text=\"Continue\"")
    page.click("text=\"Continue\"")

    log.info("Filling out landlord or agent info.")
    page.click("text=/.*Yes.*/")
    page.click("input[placeholder=\"Type your answer here...\"]")
    page.fill("input[placeholder=\"Type your answer here...\"]", "Joe Blow")
    page.click("text=\"OK\"")
    page.click("input[placeholder=\"Type your answer here...\"]")
    page.fill("input[placeholder=\"Type your answer here...\"]", "123 Blow St")
    page.click("text=\"OK\"")
    page.click("input[placeholder=\"Type your answer here...\"]")
    page.fill("input[placeholder=\"Type your answer here...\"]", "joe@blow.com")
    page.click("text=\"OK\"")
    page.click("input[placeholder=\"Type your answer here...\"]")
    page.fill("input[placeholder=\"Type your answer here...\"]", "12345678")
    page.click("text=\"OK\"")
    page.click("text=\"Continue\"")

    log.info("Filling out contact and personal info.")
    page.click("input[placeholder=\"DD\"]")
    page.fill("input[placeholder=\"DD\"]", "1")
    page.press("input[placeholder=\"DD\"]", "Tab")
    page.fill("input[placeholder=\"MM\"]", "1")
    page.press("input[placeholder=\"MM\"]", "Tab")
    page.fill("input[placeholder=\"YYYY\"]", "1990")
    page.click("text=\"OK\"")
    page.click("input[placeholder=\"Type your answer here...\"]")
    page.fill("input[placeholder=\"Type your answer here...\"]", "0411111122")
    page.click("text=\"OK\"")
    page.click("text=/.*Monday to Friday \(9am to 5pm\).*/")
    page.click("text=/.*Legal centre.*/")
    page.click("text=/.*Tenants Victoria.*/")

    log.info("Submitting form.")
    page.click("text=\"OK\"")

    log.info("Verifying submission URL.")
    page.reload()
    assert page.url.startswith("https://test-intake.anikalegal.com/submitted/")
    page.close()
    context.close()
    browser.close()

with sync_playwright() as playwright:
    run(playwright)
