# Generated by Django 5.1.1 on 2025-04-14 04:47

import os

from django.db import migrations
from microsoft.endpoints import MSGraphAPI
from microsoft.endpoints.folder import FolderEndpoint


def _rename_evictions_document_template_folder(apps, schema_editor):
    try:
        api = MSGraphAPI()
        url = os.path.join(FolderEndpoint.MIDDLE_URL, "templates/evictions")
        super(FolderEndpoint, api.folder).patch(url, {"name": "evictions-arrears"})
    except TypeError:
        # Doesn't work in test so just ignore.
        pass


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(
            _rename_evictions_document_template_folder,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
