# Generated by Django 5.1.1 on 2025-05-08 23:31
import os

from django.db import migrations
from microsoft.endpoints import MSGraphAPI
from microsoft.endpoints.folder import FolderEndpoint


def _rename_document_template_folder(apps, schema_editor):
    try:
        api = MSGraphAPI()
    except TypeError:
        pass  # Doesn't work in test so just ignore.
    else:
        path = "templates/evictions"
        if api.folder.get(path):
            url = os.path.join(FolderEndpoint.MIDDLE_URL, path)
            super(FolderEndpoint, api.folder).patch(url, {"name": "eviction"})


class Migration(migrations.Migration):
    dependencies = [
        ("microsoft", "0001_rename_health_check_document_template_folder"),
    ]

    operations = [
        migrations.RunPython(
            _rename_document_template_folder,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
