# Generated by Django 3.0.6 on 2020-05-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actionstep", "0005_actiondocument_actionstep_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actiondocument",
            name="actionstep_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
