# Generated by Django 3.1 on 2020-09-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionstep', '0006_auto_20200515_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiondocument',
            name='topic',
            field=models.CharField(choices=[('REPAIRS', 'REPAIRS'), ('RENT_REDUCTION', 'RENT_REDUCTION'), ('OTHER', 'OTHER')], max_length=32),
        ),
    ]
