# Generated by Django 3.1 on 2020-09-19 03:40

from django.db import migrations


def set_document_topic(apps, schema_editor):
    ActionDocument = apps.get_model("actionstep", "ActionDocument")
    ActionDocument.objects.exclude(topic="REPAIRS").update(topic="RENT_REDUCTION")


class Migration(migrations.Migration):

    dependencies = [
        ("actionstep", "0007_auto_20200918_0448"),
    ]

    operations = [
        migrations.RunPython(set_document_topic),
    ]
