# Generated by Django 3.1.4 on 2021-02-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionstep', '0008_auto_20200919_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiondocument',
            name='topic',
            field=models.CharField(choices=[('REPAIRS', 'REPAIRS'), ('RENT_REDUCTION', 'RENT_REDUCTION'), ('EVICTION', 'EVICTION'), ('OTHER', 'OTHER')], max_length=32),
        ),
    ]
