# Generated by Django 3.1.2 on 2020-10-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='referrer',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='client',
            name='referrer_type',
            field=models.CharField(blank=True, choices=[('LEGAL_CENTRE', 'LEGAL_CENTRE'), ('CHARITY', 'CHARITY'), ('SEARCH', 'SEARCH'), ('SOCIAL_MEDIA', 'SOCIAL_MEDIA'), ('WORD_OF_MOUTH', 'WORD_OF_MOUTH'), ('ONLINE_AD', 'ONLINE_AD')], default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='client',
            name='call_time',
            field=models.CharField(blank=True, choices=[('WEEK_DAY', 'WEEK_DAY'), ('WEEK_EVENING', 'WEEK_EVENING'), ('SATURDAY', 'SATURDAY'), ('SUNDAY', 'SUNDAY')], default='', max_length=32),
        ),
    ]
