# Generated by Django 3.1.2 on 2020-10-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201011_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='referrer_type',
            field=models.CharField(blank=True, choices=[('LEGAL_CENTRE', 'LEGAL_CENTRE'), ('CHARITY', 'CHARITY'), ('SEARCH', 'SEARCH'), ('SOCIAL_MEDIA', 'SOCIAL_MEDIA'), ('WORD_OF_MOUTH', 'WORD_OF_MOUTH'), ('ONLINE_AD', 'ONLINE_AD'), ('HOUSING_SERVICE', 'HOUSING_SERVICE')], default='', max_length=64),
        ),
    ]
