# Generated by Django 3.1.3 on 2020-11-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201029_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='fileref',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='issue',
            name='provided_legal_services',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('NO_CONTACT', 'NO_CONTACT'), ('UNRESPONSIVE', 'UNRESPONSIVE'), ('POST_CASE', 'POST_CASE'), ('CLOSED', 'CLOSED'), ('REFERRED', 'REFERRED')], default='OPEN', max_length=32),
        ),
        migrations.AddField(
            model_name='issue',
            name='status_note',
            field=models.CharField(default='', max_length=256),
        ),
    ]
