# Generated by Django 3.1.2 on 2020-11-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201115_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='status_note',
            new_name='outcome_notes',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='status',
        ),
        migrations.AddField(
            model_name='issue',
            name='outcome',
            field=models.CharField(blank=True, choices=[('UNRESPONSIVE', 'UNRESPONSIVE'), ('OUT_OF_SCOPE', 'OUT_OF_SCOPE'), ('SUCCESS', 'SUCCESS'), ('UNSUCCESSFUL', 'UNSUCCESSFUL'), ('REFERRED', 'REFERRED'), ('ESCALATION', 'ESCALATION')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='stage',
            field=models.CharField(blank=True, choices=[('ENGAGED', 'ENGAGED'), ('ADVICE', 'ADVICE'), ('POST_CASE', 'POST_CASE')], max_length=32, null=True),
        ),
    ]
