# Generated by Django 3.1.3 on 2020-11-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_reminder_sent',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='is_answered',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='is_submitted',
        ),
        migrations.AddField(
            model_name='submission',
            name='is_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
