# Generated by Django 3.1.2 on 2020-11-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201127_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancy',
            name='postcode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='tenancy',
            name='suburb',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
