# Generated by Django 3.1.2 on 2020-11-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201128_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancy',
            name='suburb',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
