# Generated by Django 3.1.4 on 2020-12-08 06:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201204_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='call_times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('WEEK_DAY', 'WEEK_DAY'), ('WEEK_EVENING', 'WEEK_EVENING'), ('SATURDAY', 'SATURDAY'), ('SUNDAY', 'SUNDAY')], max_length=32), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='client',
            name='employment_status',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='client',
            name='legal_access_and_special_circumstances',
            #name='special_circumstances', - Not in use
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=None),
        ),
        # Not in use
        #migrations.AddField(
            #model_name='client',
            #name='weekly_income',
            #field=models.IntegerField(blank=True, null=True),
        #),
        #migrations.AddField(
            #model_name='client',
            #name='weekly_rent',
            #field=models.IntegerField(blank=True, null=True),
        #),
        migrations.AddField(
            model_name='client',
            name='weekly_household_income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='welfare_reliance',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
