# Generated by Django 3.1.4 on 2020-12-10 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201208_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='call_time',
        ),
    ]
