# Generated by Django 3.1.4 on 2020-12-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_client_call_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='fileref',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='issue',
            name='outcome',
            field=models.CharField(blank=True, choices=[('UNRESPONSIVE', 'UNRESPONSIVE'), ('OUT_OF_SCOPE', 'OUT_OF_SCOPE'), ('SUCCESS', 'SUCCESS'), ('UNSUCCESSFUL', 'UNSUCCESSFUL'), ('REFERRED', 'REFERRED'), ('ESCALATION', 'ESCALATION'), ('DROPPED_OUT', 'DROPPED_OUT'), ('RESOLVED_EARLY', 'RESOLVED_EARLY'), ('UNKNOWN', 'UNKNOWN')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='outcome_notes',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='issue',
            name='stage',
            field=models.CharField(blank=True, choices=[('SUBMITTED', 'SUBMITTED'), ('ENGAGED', 'ENGAGED'), ('ADVICE', 'ADVICE'), ('POST_CASE', 'POST_CASE')], max_length=32, null=True),
        ),
    ]
