# Generated by Django 3.1.4 on 2021-03-25 01:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210219_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='can_speak_non_english',
            new_name='primary_language_non_english',
        ),
        migrations.RemoveField(
            model_name='client',
            name='gender_details',
        ),
        migrations.RemoveField(
            model_name='client',
            name='welfare_reliance',
        ),
        migrations.AddField(
            model_name='client',
            name='employment_status_new',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='client',
            name='is_multi_income_household',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='legal_access_difficulties',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='client',
            name='number_of_dependents',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='primary_language',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='client',
            name='rental_circumstances',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
