# Generated by Django 3.1.4 on 2021-03-25 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_auto_20210325_1300"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="employment_status",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="employment_status_new",
            new_name="employment_status",
        ),
    ]
