# Generated by Django 3.1.4 on 2021-03-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_client_employment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancy',
            name='is_on_lease',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
