# Generated by Django 3.1.4 on 2021-03-25 02:08

from django.db import migrations


def migrate_tenancy_is_on_lease_data(apps, schema_editor):
    Tenancy = apps.get_model("core", "Tenancy")
    for tenancy in Tenancy.objects.all():
        if tenancy.is_on_lease:
            tenancy.is_on_lease = tenancy.is_on_lease.upper()
            tenancy.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_auto_20210325_1308"),
    ]

    operations = [
        migrations.RunPython(migrate_tenancy_is_on_lease_data),
    ]
