# Generated by Django 3.1.7 on 2021-04-16 00:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210325_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='call_times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('WEEK_DAY', 'Week day'), ('WEEK_EVENING', 'Week evening'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=32), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='client',
            name='referrer_type',
            field=models.CharField(blank=True, choices=[('LEGAL_CENTRE', 'Legal centre'), ('CHARITY', 'Charity'), ('SEARCH', 'Search'), ('SOCIAL_MEDIA', 'Social media'), ('WORD_OF_MOUTH', 'Word of mouth'), ('ONLINE_AD', 'Online ad'), ('HOUSING_SERVICE', 'Housing service'), ('RADIO', 'Radio'), ('BILLBOARD', 'Billboard'), ('POSTER', 'Poster')], default='', max_length=64),
        ),
    ]
