# Generated by Django 3.1.7 on 2021-04-16 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_auto_20210416_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='actionstep_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='paralegal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='outcome',
            field=models.CharField(blank=True, choices=[('UNRESPONSIVE', 'Unresponsive'), ('OUT_OF_SCOPE', 'Out of scope'), ('SUCCESS', 'Success'), ('UNSUCCESSFUL', 'Unsuccessful'), ('REFERRED', 'Referred'), ('ESCALATION', 'Escalation'), ('DROPPED_OUT', 'Dropped out'), ('RESOLVED_EARLY', 'Resolved early'), ('UNKNOWN', 'Unknown')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='stage',
            field=models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('ENGAGED', 'Engaged'), ('ADVICE', 'Advice'), ('POST_CASE', 'Post-case')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='topic',
            field=models.CharField(choices=[('REPAIRS', 'Repairs'), ('RENT_REDUCTION', 'Rent reduction'), ('EVICTION', 'Eviction'), ('OTHER', 'Other')], max_length=32),
        ),
    ]
