# Generated by Django 3.1.7 on 2021-04-16 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0026_auto_20210416_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note_type', models.CharField(choices=[('PARALEGAL', 'Paralegal'), ('REVIEW', 'Review')], max_length=32)),
                ('text', models.CharField(blank=True, default='', max_length=2048)),
                ('event', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.issue')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
