# Generated by Django 3.2.6 on 2021-08-10 04:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_issuenote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='employment_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('WORKING_PART_TIME', 'Working part time'), ('WORKING_FULL_TIME', 'Working full time'), ('APPRENTICE', 'Apprentice'), ('LOOKING_FOR_WORK', 'Looking for work'), ('INCOME_REDUCED_COVID', 'Income reduced due to COVID-19'), ('RETIRED', 'Retired')], max_length=32), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('genderqueer', 'Genderqueer'), ('omitted', 'Omitted'), ('other', 'Other')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='legal_access_difficulties',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SUBSTANCE_ABUSE', 'Substance abuse issues'), ('CARING', 'Caring for another'), ('DISABILITY', 'Disability'), ('OTHER', 'Other')], max_length=32), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='client',
            name='rental_circumstances',
            field=models.CharField(blank=True, choices=[('SOLO', 'Renting solo'), ('FLATMATES', 'Renting with flatmates'), ('PARTNER', 'Renting with a partner'), ('FAMILY', 'Renting with family'), ('OTHER', 'Other')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='client',
            name='special_circumstances',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CENTRELINK', 'Centrelink'), ('MENTAL_ILLNESS_OR_DISABILITY', 'Mental illness or disability'), ('PUBLIC_HOUSING', 'Public housing'), ('FAMILY_VIOLENCE', 'Risk of family violence'), ('HEALTH_CONDITION', 'Health condition'), ('REFUGEE', 'Refugee')], max_length=32), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='is_on_lease',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('VERBAL', 'A verbal agreement')], max_length=32, null=True),
        ),
    ]
