# Generated by Django 3.2.6 on 2021-08-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20210810_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuenote',
            name='actionstep_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
