# Generated by Django 3.2.6 on 2021-08-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_issuenote_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuenote',
            name='note_type',
            field=models.CharField(choices=[('PARALEGAL', 'File note'), ('REVIEW', 'Case review'), ('PERFORMANCE', 'Paralegal performance review')], max_length=32),
        ),
    ]
