# Generated by Django 3.2.6 on 2021-08-25 03:38

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0032_auto_20210824_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuenote',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='issuenote',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issuenote',
            name='note_type',
            field=models.CharField(choices=[('PARALEGAL', 'File note'), ('REVIEW', 'Case review'), ('PERFORMANCE', 'Paralegal performance review'), ('EVENT', 'System generated event')], max_length=32),
        ),
        migrations.CreateModel(
            name='IssueEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('prev_is_open', models.BooleanField(blank=True, null=True)),
                ('next_is_open', models.BooleanField(blank=True, null=True)),
                ('prev_stage', models.CharField(blank=True, max_length=32, null=True)),
                ('next_stage', models.CharField(blank=True, max_length=32, null=True)),
                ('event_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PARALEGAL', 'Paralegal assigned'), ('STAGE', 'Stage change'), ('OPEN', 'Open change')], max_length=32), blank=True, default=list, size=None)),
                ('actionstep_id', models.IntegerField(blank=True, null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.issue')),
                ('next_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prev_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
