# Generated by Django 3.2.6 on 2021-08-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_auto_20210825_1338"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OUT_OF_SCOPE", "Out of scope"),
                    ("CHANGE_OF_SCOPE", "Change of scope"),
                    ("RESOLVED_EARLY", "Resolved early"),
                    ("CHURNED", "Churned"),
                    ("UNKNOWN", "Unknown"),
                    ("SUCCESSFUL", "Successful"),
                    ("UNSUCCESSFUL", "Unsuccessful"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="stage",
            field=models.CharField(
                choices=[
                    ("UNSTARTED", "Not started"),
                    ("CLIENT_AGREEMENT", "Client agreement"),
                    ("ADVICE", "Drafting advice"),
                    ("FORMAL_LETTER", "Formal letter sent"),
                    ("NEGOTIATIONS", "Negotiations"),
                    ("VCAT_CAV", "VCAT/CAV"),
                    ("POST_CASE_INTERVIEW", "Post-case interview"),
                    ("CLOSED", "Closed"),
                ],
                default="UNSTARTED",
                max_length=32,
            ),
        ),
    ]
