# Generated by Django 3.2.7 on 2021-12-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_issue_is_sharepoint_set_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuenote',
            name='note_type',
            field=models.CharField(choices=[('PARALEGAL', 'File note'), ('REVIEW', 'Case review'), ('PERFORMANCE', 'Paralegal performance review'), ('EVENT', 'System generated event'), ('EMAIL', 'Email'), ('CONFLICT_CHECK', 'Conflict check')], max_length=32),
        ),
    ]
