# Generated by Django 3.2.12 on 2022-03-07 05:10

from django.db import migrations


def parse_outcome_text(apps, schema_editor):
    IssueNote = apps.get_model("core", "IssueNote")
    notes = IssueNote.objects.filter(note_type="CONFLICT_CHECK").all()
    for note in notes:
        if note.text.startswith("Outcome: cleared."):
            note.note_type = "CONFLICT_CHECK_SUCCESS"
        else:
            note.note_type = "CONFLICT_CHECK_FAILURE"

        note.text = ".".join([t.strip() for t in note.text.split(".")[1:]])
        note.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_alter_issue_topic"),
    ]

    operations = [
        migrations.RunPython(parse_outcome_text),
    ]
