# Generated by Django 3.2.12 on 2022-03-09 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0040_conflict_check_migrate"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="lawyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lawyer_issues",
                related_query_name="lawyer_issue",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="issuenote",
            name="note_type",
            field=models.CharField(
                choices=[
                    ("PARALEGAL", "File note"),
                    ("REVIEW", "Case review"),
                    ("PERFORMANCE", "Paralegal performance review"),
                    ("EVENT", "System generated event"),
                    ("EMAIL", "Email"),
                    ("CONFLICT_CHECK_SUCCESS", "Conflict check cleared"),
                    ("CONFLICT_CHECK_FAILURE", "Conflict check not cleared"),
                    ("ELIGIBILITY_CHECK_SUCCESS", "Eligibility check cleared"),
                    ("ELIGIBILITY_CHECK_FAILURE", "Eligibility check not cleared"),
                ],
                max_length=32,
            ),
        ),
    ]
