# Generated by Django 4.0.4 on 2022-07-12 11:39

import django.core.serializers.json
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20220309_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoEmailAdmin',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('is_reminder_sent', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
