# Generated by Django 4.0.4 on 2022-05-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20220309_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_welcome_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
