# Generated by Django 4.0.4 on 2022-07-14 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_noemailsubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoEmailSubmission',
        ),
    ]
