# Generated by Django 4.0.4 on 2022-05-20 08:24

from django.db import migrations


def set_welcome_flag(apps, schema_editor):
    Issue = apps.get_model("core", "Issue")
    Issue.objects.all().update(is_welcome_email_sent=True)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_issue_is_welcome_email_sent"),
    ]

    operations = [
        migrations.RunPython(set_welcome_flag),
    ]
