# Generated by Django 4.0.4 on 2022-05-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20220520_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('GENDERQUEER', 'Genderqueer'), ('OMITTED', 'Omitted'), ('OTHER', 'Other')], max_length=64, null=True),
        ),
    ]
