# Generated by Django 4.0.4 on 2022-05-31 06:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_client_notes_alter_client_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='employment_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('WORKING_PART_TIME', 'Working part time'), ('WORKING_FULL_TIME', 'Working full time'), ('STUDENT', 'Student'), ('APPRENTICE', 'Apprentice'), ('LOOKING_FOR_WORK', 'Looking for work'), ('INCOME_REDUCED_COVID', 'Income reduced due to COVID-19'), ('RETIRED', 'Retired')], max_length=32), blank=True, default=list, size=None),
        ),
    ]
