# Generated by Django 4.0.4 on 2022-05-31 06:36

from django.db import migrations


def client_gender_caps(apps, schema_editor):
    Client = apps.get_model("core", "Client")
    for client in Client.objects.all():
        if client.gender:
            client.gender = client.gender.upper()
            client.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_alter_client_employment_status"),
    ]

    operations = [
        migrations.RunPython(client_gender_caps),
    ]
