# Generated by Django 4.0.4 on 2022-07-06 05:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_client_gender_caps"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="is_multi_income_household",
        ),
        migrations.AddField(
            model_name="client",
            name="centrelink_support",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="client",
            name="eligibility_circumstances",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("HOUSING", "Public housing"),
                        ("MENTAL_ILLNESS", "Mental illness"),
                        ("INTELLECTUAL_DISABILITY", "Intellectual disability"),
                        ("PHYSICAL_DISABILITY", "Physical disability"),
                        ("VISA", "Eligible visa type"),
                        ("FAMILY_VIOLENCE", "Family violence"),
                        ("UNEXPECTED_CIRCUMSTANCE", "Unexpected circumstance"),
                        ("SUBSTANCE_ABUSE", "Substance abuse"),
                        (
                            "ABORIGINAL_OR_TORRES_STRAIT",
                            "Aboriginal or Torres Strait Islander",
                        ),
                        ("RENTING", "Renting in a remote or regional location"),
                        ("STRUGGLING", "Struggling with bills"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="eligibility_notes",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
        migrations.AddField(
            model_name="client",
            name="requires_interpreter",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="client",
            name="employment_status",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("WORKING_PART_TIME", "Working part time"),
                        ("WORKING_FULL_TIME", "Working full time"),
                        ("STUDENT", "Student"),
                        ("APPRENTICE", "Apprentice"),
                        ("LOOKING_FOR_WORK", "Looking for work"),
                        ("INCOME_REDUCED_COVID", "Income reduced due to COVID-19"),
                        ("RETIRED", "Retired"),
                        ("PARENT", "Full time parent"),
                        ("UNEMPLOYED", "Currently unemployed"),
                        ("NOT_LOOKING_FOR_WORK", "Not looking for work"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="gender",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="legal_access_difficulties",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="number_of_dependents",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="special_circumstances",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
