# Generated by Django 4.0.4 on 2022-07-06 05:35
from django.db import migrations

GENDER_MAP = {
    "MALE": "Male",
    "FEMALE": "Female",
    "GENDERQUEER": "Genderqueer",
    "OMITTED": "Omitted",
    "OTHER": "Other",
}


LEGAL_CIRC_MAP = {
    "SUBSTANCE_ABUSE": "SUBSTANCE_ABUSE",
}
SPECIAL_CIRC_MAP = {
    "MENTAL_ILLNESS_OR_DISABILITY": "MENTAL_ILLNESS",
    "PUBLIC_HOUSING": "HOUSING",
    "FAMILY_VIOLENCE": "FAMILY_VIOLENCE",
    "HEALTH_CONDITION": "PHYSICAL_DISABILITY",
    "REFUGEE": "VISA",
}


def migrate_intake_data(apps, schema_editor):
    Client = apps.get_model("core", "Client")
    for client in Client.objects.all():
        # Map gender
        client.gender = GENDER_MAP.get(client.gender, "OMITTED")
        # Grab centrelink info
        if "CENTRELINK" in client.special_circumstances:
            client.centrelink_support = True

        # Consolidate eligibility circumstances.
        circs = []
        for circ in client.special_circumstances:
            new_circ = SPECIAL_CIRC_MAP.get(circ)
            if new_circ:
                circs.append(new_circ)

        for circ in client.legal_access_difficulties:
            new_circ = LEGAL_CIRC_MAP.get(circ)
            if new_circ:
                circs.append(new_circ)

        client.eligibility_circumstances = circs
        client.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_update_fields_from_intake"),
    ]

    operations = [migrations.RunPython(migrate_intake_data)]
