# Generated by Django 4.0.9 on 2023-04-02 09:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_migrate_elibility_circs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueevent',
            name='event_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('LAWYER', 'Lawyer assigned'), ('PARALEGAL', 'Paralegal assigned'), ('STAGE', 'Stage change'), ('OPEN', 'Open change')], max_length=32), blank=True, default=list, size=None),
        ),
    ]
