# Generated by Django 4.0.9 on 2023-04-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_issue_support_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='support_contact_preferences',
            field=models.CharField(blank=True, choices=[('DIRECT_ONLY', 'Contact me directly instead of the renter'), ('COPY_ME_IN', 'Contact the renter directly but copy me into every interaction'), ('PERIODIC_UPDATE', 'Contact the renter directly but give me a fortnightly update'), ('FINAL_UPDATE', 'Contact the renter directly and give me an update only once the matter is finalised.'), ('RENTER_MIA', "Contact the renter directly but you may contact me if you can't contact the renter.")], default='', max_length=16),
        ),
    ]
