# Generated by Django 4.0.10 on 2023-07-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_split_issue_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issueevent',
            name='event_types',
        ),
        migrations.AlterField(
            model_name='issue',
            name='topic',
            field=models.CharField(choices=[('REPAIRS', 'Repairs'), ('BONDS', 'Bonds'), ('EVICTION', 'Eviction'), ('HEALTH_CHECK', 'Housing Health Check'), ('RENT_REDUCTION', 'Rent reduction'), ('OTHER', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='issueevent',
            name='event_type',
            field=models.CharField(choices=[('LAWYER', 'Lawyer assigned'), ('PARALEGAL', 'Paralegal assigned'), ('STAGE', 'Stage change'), ('OPEN', 'Open change')], max_length=32),
        ),
    ]
