# Generated by Django 4.0.10 on 2023-11-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_remove_issueevent_event_types_alter_issue_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
