# Generated by Django 4.0.10 on 2023-11-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_client_preferred_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pronouns',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
