# Generated by Django 4.0.10 on 2023-11-27 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_migrate_tenancy_to_case"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenancy",
            name="client",
        ),
        migrations.AlterField(
            model_name="issue",
            name="tenancy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.tenancy"
            ),
        ),
    ]
