# Generated by Django 4.0.10 on 2023-12-21 01:51

import django.contrib.postgres.fields
from django.db import migrations, models


import logging
from pathlib import Path

LOGGER = logging.getLogger("migration")
NAME = Path(__file__).stem


def _migrate_employment_status_to_case(apps, schema_editor):
    Client = apps.get_model("core", "Client")
    Issue = apps.get_model("core", "Issue")

    LOGGER.info("Migration: %s", NAME)

    for client in Client.objects.all():
        if client.employment_status is not None:
            issues = Issue.objects.filter(client=client)

            # The client has multiple issues. We don't which one the employment
            # status "belongs" to, so we make a note.
            if issues.count() > 1:
                LOGGER.info("%s: CLIENT %s - MULTIPLE_ISSUES", NAME, client.pk)

            for issue in issues:
                issue.employment_status = client.employment_status
                issue.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0060_remove_client_weekly_rent_issue_tenancy_weekly_rent"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="employment_status",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("WORKING_PART_TIME", "Working part time"),
                        ("WORKING_FULL_TIME", "Working full time"),
                        ("STUDENT", "Student"),
                        ("APPRENTICE", "Apprentice"),
                        ("LOOKING_FOR_WORK", "Looking for work"),
                        ("INCOME_REDUCED_COVID", "Income reduced due to COVID-19"),
                        ("RETIRED", "Retired"),
                        ("PARENT", "Full time parent"),
                        ("UNEMPLOYED", "Currently unemployed"),
                        ("NOT_LOOKING_FOR_WORK", "Not looking for work"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.RunPython(
            _migrate_employment_status_to_case, reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="client",
            name="employment_status",
        ),
    ]
