# Generated by Django 4.0.10 on 2024-01-30 05:36

from django.db import migrations, models


def _migrate_requires_interpreter_values(apps, schema_editor):
    Client = apps.get_model("core", "Client")

    Client.objects.filter(requires_interpreter="false").update(
        requires_interpreter="NO"
    )

    Client.objects.filter(requires_interpreter="true").update(
        requires_interpreter="YES_CONFIRM"
    )

    Client.objects.filter(requires_interpreter="").update(
        requires_interpreter="UNKNOWN"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0064_remove_client_rental_circumstances_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="requires_interpreter",
            field=models.CharField(
                choices=[
                    ("NO", "No"),
                    ("YES_WRITTEN", "Yes (written communication)"),
                    ("YES_SPOKEN", "Yes (spoken communiction)"),
                    ("YES_WRITTEN_SPOKEN", "Yes (written and spoken)"),
                    ("YES_CONFIRM", "Yes (Confirm if written and/or spoken)"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=32,
            ),
        ),
        migrations.RunPython(
            _migrate_requires_interpreter_values, reverse_code=migrations.RunPython.noop
        ),
    ]
