# Generated by Django 4.0.10 on 2024-01-31 00:26

from django.db import migrations, models


def _migrate_is_aboriginal_or_torres_strait_islander_values(apps, schema_editor):
    Client = apps.get_model("core", "Client")

    Client.objects.filter(is_aboriginal_or_torres_strait_islander="false").update(
        is_aboriginal_or_torres_strait_islander="NO"
    )

    Client.objects.filter(is_aboriginal_or_torres_strait_islander="true").update(
        is_aboriginal_or_torres_strait_islander="YES_CONFIRM"
    )

    Client.objects.filter(is_aboriginal_or_torres_strait_islander="").update(
        is_aboriginal_or_torres_strait_islander="NOT_STATED"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0065_alter_client_requires_interpreter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="is_aboriginal_or_torres_strait_islander",
            field=models.CharField(
                choices=[
                    ("NO", "No"),
                    ("YES_ABORIGINAL", "Yes, Aboriginal"),
                    ("YES_TSI", "Yes, Torres Strait Islander"),
                    (
                        "YES_ABORIGINAL_AND_TSI",
                        "Yes, Aboriginal and Torres Strait Islander",
                    ),
                    (
                        "YES_CONFIRM",
                        "Yes (Confirm if Aboriginal and/or Torres Strait Islander)",
                    ),
                    ("PREFER_NOT_TO_ANSWER", "Prefer not to answer"),
                    ("NOT_STATED", "Not Stated"),
                ],
                default="NOT_STATED",
                max_length=32,
            ),
        ),
        migrations.RunPython(
            _migrate_is_aboriginal_or_torres_strait_islander_values,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
