# Generated by Django 4.0.10 on 2024-03-12 10:01

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_issue_employment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='answers',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
