# Generated by Django 4.0.10 on 2024-05-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_alter_issue_employment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="outcome_notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
