# Generated by Django 5.1.1 on 2024-10-23 23:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_alter_issue_outcome_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "modified_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DISCRETE", "Discrete service"),
                            ("ONGOING", "Ongoing service"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("LEGAL_ADVICE", "Legal advice"),
                            ("LEGAL_TASK", "Legal task"),
                            ("GENERAL_INFORMATION", "Information"),
                            ("GENERAL_REFERRAL_SIMPLE", "Referral (Simple)"),
                            ("GENERAL_REFERRAL_FACILITATED", "Referral (Facilitated)"),
                            ("LEGAL_SUPPORT", "Legal support"),
                            (
                                "REPRESENTATION_COURT_TRIBUNAL",
                                "Court or tribunal representation",
                            ),
                            ("REPRESENTATION_OTHER", "Other representation"),
                        ],
                        max_length=64,
                    ),
                ),
                ("started_at", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("count", models.IntegerField(default=1)),
                ("finished_at", models.DateField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.issue"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
