# Generated by Django 5.1.1 on 2024-09-18 06:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_alter_issue_outcome_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "modified_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DISCRETE", "Discrete legal service"),
                            ("ONGOING", "Ongoing legal service"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "sub_type",
                    models.CharField(
                        choices=[
                            ("ADVICE", "Legal advice"),
                            ("TASK", "Legal task"),
                            ("INFORMATION", "Information"),
                            ("REFERRAL", "Referral"),
                            ("CASEWORK", "Ongoing legal casework"),
                            (
                                "COURT_REPRESENTATION",
                                "Court or tribunal representation",
                            ),
                            ("OTHER_REPRESENTATION", "Other representation services"),
                        ],
                        max_length=32,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.issue"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
