# Generated by Django 5.1.1 on 2024-11-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_service_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "Service created"),
                    ("UPDATE", "Service updated"),
                    ("DELETE", "Service deleted"),
                ],
                max_length=32,
            ),
        ),
    ]
