# Generated by Django 5.1.1 on 2025-03-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_alter_serviceevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenancy",
            name="is_on_lease",
            field=models.CharField(
                blank=True,
                choices=[
                    ("YES", "Yes"),
                    ("NO", "No"),
                    ("VERBAL", "A verbal agreement"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
