# Generated by Django 5.1.1 on 2024-11-14 23:07

import core.models.upload
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_alter_serviceevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="file",
            field=models.FileField(
                storage=storages.backends.s3.S3Storage(querystring_expire=604800),
                upload_to=core.models.upload.get_s3_key,
            ),
        ),
    ]
