# Generated by Django 4.0.10 on 2024-04-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_alter_serviceevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issueevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "Created"),
                    ("LAWYER", "Lawyer assigned"),
                    ("PARALEGAL", "Paralegal assigned"),
                    ("STAGE", "Stage change"),
                    ("OPEN", "Open change"),
                ],
                max_length=32,
            ),
        ),
    ]
