# Generated by Django 5.1.1 on 2025-04-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_alter_tenancy_is_on_lease"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="contact_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="client",
            name="contact_restriction",
            field=models.TextField(
                blank=True,
                choices=[
                    ("DO_NOT_CONTACT", "Do not contact"),
                    ("DO_NOT_CONTACT_MARKETING", "Do not contact for marketing"),
                    (
                        "DO_NOT_CONTACT_ACTION_RESEARCH",
                        "Do not contact for action research",
                    ),
                ],
                default="",
            ),
        ),
    ]
