# Generated by Django 5.1.1 on 2025-06-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_client_contact_notes_client_contact_restriction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="referrer_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LEGAL_CENTRE", "Legal centre"),
                    ("COMMUNITY_ORGANISATION", "Community organisation"),
                    ("SEARCH", "Search"),
                    ("SOCIAL_MEDIA", "Social media"),
                    ("WORD_OF_MOUTH", "Word of mouth"),
                    ("ONLINE_AD", "Online ad"),
                    ("HOUSING_SERVICE", "Housing service"),
                    ("RADIO", "Radio"),
                    ("BILLBOARD", "Billboard"),
                    ("POSTER", "Poster"),
                    ("RETURNING_CLIENT", "Returning client"),
                ],
                default="",
                max_length=64,
            ),
        ),
    ]
