# Generated by Django 5.1.1 on 2025-05-09 01:26

from django.db import migrations, models


def _set_existing_eviction_subtype(apps, schema_editor):
    Issue = apps.get_model("core", "Issue")
    Issue.objects.filter(topic="EVICTION", subtopic__exact="").update(
        subtopic="ARREARS"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0076_client_contact_notes_client_contact_restriction"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="subtopic",
            field=models.CharField(
                blank=True,
                choices=[("ARREARS", "Arrears"), ("RETALIATORY", "Retaliatory")],
                default="",
                max_length=32,
            ),
        ),
        migrations.RunPython(
            _set_existing_eviction_subtype,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
