# Generated by Django 5.1.1 on 2025-04-02 22:30

from django.db import migrations


def _change_wagtail_default_locale(apps, schema_editor):
    try:
        Locale = apps.get_model("wagtailcore", "Locale")
        Locale.objects.filter(language_code="en").update(language_code="en-au")
    except(Exception):
        pass


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0076_alter_issueevent_event_type"),
    ]

    operations = [
        migrations.RunPython(
            _change_wagtail_default_locale,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
