# Generated by Django 5.1.1 on 2025-05-15 03:20

import core.models.document_template
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0077_issue_subtopic"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "modified_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("REPAIRS", "Repairs"),
                            ("BONDS", "Bonds"),
                            ("EVICTION", "Eviction"),
                            ("HEALTH_CHECK", "Housing Health Check"),
                            ("RENT_REDUCTION", "Rent reduction"),
                            ("OTHER", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "subtopic",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ARREARS", "Arrears"),
                            ("RETALIATORY", "Retaliatory"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=256,
                        storage=core.models.document_template.DocumentTemplate._get_storage_class,
                        upload_to=core.models.document_template.DocumentTemplate._get_upload_to,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
