# Generated by Django 5.1.1 on 2025-04-14 03:04

from django.db import migrations, models


def _migrate_legacy_eviction_value(apps, schema_editor):
    Issue = apps.get_model("core", "Issue")
    Issue.objects.filter(topic="EVICTION").update(topic="EVICTION_ARREARS")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0077_alter_issue_referrer_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="topic",
            field=models.CharField(
                choices=[
                    ("REPAIRS", "Repairs"),
                    ("BONDS", "Bonds"),
                    ("EVICTION_ARREARS", "Eviction (Arrears)"),
                    ("EVICTION_RETALIATORY", "Eviction (Retaliatory)"),
                    ("HEALTH_CHECK", "Housing Health Check"),
                    ("RENT_REDUCTION", "Rent reduction"),
                    ("OTHER", "Other"),
                ],
                max_length=32,
            ),
        ),
        migrations.RunPython(
            _migrate_legacy_eviction_value,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
