# Generated by Django 5.1.1 on 2025-05-15 03:22
import os
from urllib.parse import quote

from django.db import migrations
from django.utils.text import slugify
from microsoft.endpoints import MSGraphAPI


def _set_initial_data(apps, schema_editor):
    DocumentTemplate = apps.get_model("core", "DocumentTemplate")
    api = MSGraphAPI()
    if api.is_available():
        for topic in ["REPAIRS", "BONDS", "EVICTION_ARREARS", "HEALTH_CHECK"]:
            folder = slugify(topic)
            files = api.folder.get_children(f"templates/{folder}")
            for file in files:
                name = file["name"]
                path = os.path.join(folder, quote(name))
                DocumentTemplate.objects.create(topic=topic, file=path, name=name)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0078_documenttemplate"),
        ("microsoft", "0001_rename_evictions_document_template_folder"),
        ("microsoft", "0002_rename_health_check_document_template_folder"),
    ]

    operations = [
        migrations.RunPython(
            _set_initial_data,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
