# Generated by Django 5.1.1 on 2025-05-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0080_documenttemplate_initial_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="is_alert_sent",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="issue",
            name="is_welcome_email_sent",
            field=models.BooleanField(default=True),
        ),
    ]
