# Generated by Django 5.1.1 on 2025-06-03 05:52

from django.db import migrations
from django.contrib.postgres.operations import CreateCollation


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0081_alter_issue_is_alert_sent_and_more"),
    ]
    operations = [
        CreateCollation(name="natural", provider="icu", locale="en@colNumeric=yes"),
    ]
