# Generated by Django 5.1.1 on 2025-06-12 06:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0082_add_db_collation_natural"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="eligibility_circumstances",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("HOUSING", "Public housing"),
                        ("SINGLE_PARENT", "Single Parent"),
                        ("MENTAL_ILLNESS", "Mental illness"),
                        ("INTELLECTUAL_DISABILITY", "Intellectual disability"),
                        ("PHYSICAL_DISABILITY", "Physical disability"),
                        ("VISA", "Eligible visa type"),
                        ("FAMILY_VIOLENCE", "Family violence"),
                        ("UNEXPECTED_CIRCUMSTANCE", "Unexpected circumstance"),
                        ("SUBSTANCE_ABUSE", "Substance abuse"),
                        (
                            "ABORIGINAL_OR_TORRES_STRAIT",
                            "Aboriginal or Torres Strait Islander",
                        ),
                        ("RENTING", "Renting in a remote or regional location"),
                        ("STRUGGLING", "Struggling with bills"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
