# Generated by Django 5.1.1 on 2025-06-16 00:57

import re

from django.db import migrations


def _remove_issue_answer_prefix(apps, schema_editor):
    Issue = apps.get_model("core", "Issue")
    for issue in Issue.objects.all():
        if issue.answers is None:
            issue.answers = {}
        else:
            fixed_answers = {}
            for key, value in issue.answers.items():
                # Remove leading text up to & including the first underscore.
                key = re.sub(r"^[^_]*_", r"", key)
                if issue.topic == "RENT_REDUCTION":
                    key = re.sub(r"^[^_]*_", r"", key)
                fixed_answers[key] = value
            issue.answers = fixed_answers

        issue.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0083_alter_client_eligibility_circumstances"),
    ]

    operations = [
        migrations.RunPython(
            _remove_issue_answer_prefix,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
