# Generated by Django 5.1.1 on 2025-07-11 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0085_unquote_document_template_file_names"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documenttemplate",
            name="name",
        ),
    ]
