# Generated by Django 5.1.1 on 2025-05-06 06:50

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0086_remove_documenttemplate_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="answers",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder, null=True
            ),
        ),
    ]
