# Generated by Django 5.1.1 on 2025-06-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0087_alter_issue_answers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="pronouns",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
