# Generated by Django 5.1.1 on 2025-09-30 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0088_alter_client_pronouns"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="submission",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.submission",
            ),
        ),
    ]
