# Generated by Django 5.1.1 on 2025-09-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0090_auditevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuedate",
            name="hearing_location",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="issuedate",
            name="hearing_type",
            field=models.CharField(
                blank=True,
                choices=[("IN_PERSON", "In person"), ("VIRTUAL", "Virtual")],
                default="",
                max_length=32,
            ),
        ),
    ]
