# Generated by Django 5.1.1 on 2025-09-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0091_issuedate_hearing_location_issuedate_hearing_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuedate",
            name="type",
            field=models.CharField(
                choices=[
                    ("FILING_DEADLINE", "Filing deadline"),
                    ("HEARING_LISTED", "Hearing listed"),
                    ("LIMITATION", "Limitation"),
                    ("NTV_TERMINATION", "NTV termination"),
                    ("OTHER", "Other"),
                ],
                max_length=32,
            ),
        ),
    ]
