# Generated by Django 5.1.1 on 2025-10-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0092_alter_issuedate_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="requires_interpreter",
            field=models.CharField(
                choices=[
                    ("NO", "No"),
                    ("YES_WRITTEN", "Yes (written communication)"),
                    ("YES_SPOKEN", "Yes (spoken communication)"),
                    ("YES_WRITTEN_SPOKEN", "Yes (written and spoken)"),
                    ("YES_CONFIRM", "Yes (Confirm if written and/or spoken)"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=32,
            ),
        ),
    ]
