# Generated by Django 5.1.1 on 2026-05-02 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0096_alter_issueevent_next_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="support_worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="support_worker_issue",
                to="core.person",
            ),
        ),
        migrations.AlterField(
            model_name="tenancy",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="agent_tenancy",
                to="core.person",
            ),
        ),
        migrations.AlterField(
            model_name="tenancy",
            name="landlord",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="landlord_tenancy",
                to="core.person",
            ),
        ),
    ]
