# Generated by Django 5.1.1 on 2026-05-12 04:58

from django.db import migrations, models


def _migrate_weekly_income_to_annual_income_range(apps, schema_editor):
    Issue = apps.get_model("core", "Issue")

    for issue in Issue.objects.filter(weekly_income__isnull=False):
        if issue.weekly_income < 770:  # 770 x 52 = 40,040
            issue.annual_income_range = "UNDER_40K"
        elif issue.weekly_income < 1250:  # 1250 x 52 = 65,000
            issue.annual_income_range = "FROM_40K_TO_64K"
        elif issue.weekly_income < 1731:  # 1731 x 52 = 90,012
            issue.annual_income_range = "FROM_65K_TO_89K"
        elif issue.weekly_income < 2193:  # 2193 x 52 = 114,036
            issue.annual_income_range = "FROM_90K_TO_114K"
        elif issue.weekly_income < 2674:  # 2674 x 52 = 139,048
            issue.annual_income_range = "FROM_115K_TO_139K"
        elif issue.weekly_income < 2981:  # 2981 x 52 = 155,012
            issue.annual_income_range = "FROM_140K_TO_155K"
        else:
            issue.annual_income_range = "OVER_155K"
        issue.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0097_alter_issue_support_worker_alter_tenancy_agent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="annual_income_range",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UNDER_40K", "Under $40,000"),
                    ("FROM_40K_TO_64K", "$40,000 - $64,000"),
                    ("FROM_65K_TO_89K", "$65,000 - $89,000"),
                    ("FROM_90K_TO_114K", "$90,000 - $114,000"),
                    ("FROM_115K_TO_139K", "$115,000 - $139,000"),
                    ("FROM_140K_TO_155K", "$140,000 - $155,000"),
                    ("OVER_155K", "Over $155,000"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.RunPython(
            _migrate_weekly_income_to_annual_income_range,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
