# Generated by Django 5.1.1 on 2026-07-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0098_issue_annual_income_range"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="eligibility_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="client",
            name="primary_language",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
