# Generated by Django 5.1.1 on 2026-07-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0099_alter_client_eligibility_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="annual_income_range",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UNDER_40K", "Under $40,000"),
                    ("FROM_40K_TO_64K", "$40,000 - $64,999"),
                    ("FROM_65K_TO_89K", "$65,000 - $89,999"),
                    ("FROM_90K_TO_114K", "$90,000 - $114,999"),
                    ("FROM_115K_TO_139K", "$115,000 - $139,999"),
                    ("FROM_140K_TO_155K", "$140,000 - $155,000"),
                    ("OVER_155K", "Over $155,000"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
