/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/submission/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['createIntakeSubmission']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/submission/{id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getIntakeSubmission']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: operations['updateIntakeSubmission']
    trace?: never
  }
  '/api/submission/{id}/submit/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['submitIntakeSubmission']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/upload/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['createIntakeUpload']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/webhooks/intake-noemail/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['createIntakeNoEmailContact']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/clerk/api/submission/{id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getSubmission']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/clerk/api/case/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getCases']
    put?: never
    post: operations['createCase']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/clerk/api/case/{id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getCase']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: operations['updateCase']
    trace?: never
  }
  '/clerk/api/case/{id}/note/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['createCaseNote']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/clerk/api/case/{id}/docs/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getCaseDocuments']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/clerk/api/case/{id}/services/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getCaseServices']
    put?: never
    post: operations['createCaseService']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/clerk/api/case/{id}/services/{service_id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getCaseService']
    put?: never
    post?: never
    delete: operations['deleteCaseService']
    options?: never
    head?: never
    patch: operations['updateCaseService']
    trace?: never
  }
  '/clerk/api/email/{id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getEmailThreads']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/clerk/api/email/{id}/create/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['createEmail']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/clerk/api/email/{id}/{email_id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getEmail']
    put?: never
    post?: never
    delete: operations['deleteEmail']
    options?: never
    head?: never
    patch: operations['updateEmail']
    trace?: never
  }
  '/clerk/api/email/{id}/{email_id}/attachment/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['createEmailAttachment']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/clerk/api/email/{id}/{email_id}/attachment/{attachment_id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete: operations['deleteEmailAttachment']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/clerk/api/email/{id}/{email_id}/attachment/{attachment_id}/sharepoint/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['uploadEmailAttachmentToSharepoint']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/clerk/api/email/{id}/{email_id}/attachment/sharepoint/{sharepoint_id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['downloadEmailAttachmentFromSharepoint']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/clerk/api/note/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getNotes']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/clerk/api/person/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getPeople']
    put?: never
    post: operations['createPerson']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/clerk/api/person/{id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getPerson']
    put?: never
    post?: never
    delete: operations['deletePerson']
    options?: never
    head?: never
    patch: operations['updatePerson']
    trace?: never
  }
  '/clerk/api/date/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getCaseDates']
    put?: never
    post: operations['createCaseDate']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/clerk/api/date/{id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getCaseDate']
    put?: never
    post?: never
    delete: operations['deleteCaseDate']
    options?: never
    head?: never
    patch: operations['updateCaseDate']
    trace?: never
  }
  '/clerk/api/tenancy/{id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getTenancy']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: operations['updateTenancy']
    trace?: never
  }
  '/clerk/api/client/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getClients']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/clerk/api/client/{id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getClient']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: operations['updateClient']
    trace?: never
  }
  '/clerk/api/account/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getUsers']
    put?: never
    post: operations['createUser']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/clerk/api/account/{id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getUser']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: operations['updateUser']
    trace?: never
  }
  '/clerk/api/account/{id}/perms/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getUserAccountPermissions']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/clerk/api/account/{id}/perms-resync/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['resyncUserAccountPermissions']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/clerk/api/account/potential/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getPotentialUsers']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/clerk/api/template-email/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getEmailTemplates']
    put?: never
    post: operations['createEmailTemplate']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/clerk/api/template-email/{id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getEmailTemplate']
    put?: never
    post?: never
    delete: operations['deleteEmailTemplate']
    options?: never
    head?: never
    patch: operations['updateEmailTemplate']
    trace?: never
  }
  '/clerk/api/template-notify/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getNotificationTemplates']
    put?: never
    post: operations['createNotificationTemplate']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/clerk/api/template-notify/{id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getNotificationTemplate']
    put?: never
    post?: never
    delete: operations['deleteNotificationTemplate']
    options?: never
    head?: never
    patch: operations['updateNotificationTemplate']
    trace?: never
  }
  '/clerk/api/template-doc/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getDocumentTemplates']
    put?: never
    post: operations['createDocumentTemplate']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/clerk/api/template-doc/{id}/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete: operations['deleteDocumentTemplate']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/clerk/api/template-doc/{id}/rename-file/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch: operations['renameDocumentTemplate']
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    IntakeSubmissionCreate: {
      answers: {
        [key: string]: unknown
      }
    }
    IntakeSubmission: {
      /** Format: uuid */
      id: string
      /** @description Intake form answers keyed by UPPER_SNAKE_CASE question name. The effective schema is owned by the survey definition in intake/src/ and consumed by core.services.submission.process_submission. */
      answers: {
        [key: string]: unknown
      }
    }
    /** @description Standardized error envelope produced by drf-standardized-errors. Every 4xx/5xx response shares this shape: a `type` describing the error category and a list of one or more individual `errors`. */
    Error: {
      /**
       * @description The category of error that occurred.
       * @example validation_error
       * @enum {string}
       */
      type: 'validation_error' | 'client_error' | 'server_error'
      /** @description The individual errors that make up this response. */
      errors: {
        /**
         * @description A machine-readable code identifying the error.
         * @example required
         */
        code: string
        /**
         * @description A human-readable description of the error.
         * @example This field is required.
         */
        detail: string
        /**
         * @description The name of the field that raised the error, or null for errors not tied to a specific field. Non-field validation errors use "non_field_errors".
         * @example email
         */
        attr: string | null
      }[]
    }
    IntakeFileUpload: {
      /** Format: uuid */
      id: string
      file: string
      /** Format: uuid */
      issue: string | null
    }
    BooleanYesNo: {
      /** @enum {string} */
      label: 'Yes' | 'No'
      value: boolean
    }
    ChoiceDisplay: {
      label: string
      value: string
    }
    SubmissionPerson: {
      name?: string | null
      address?: string | null
      email?: string | null
      phone_number?: string | null
      support_contact_preferences?:
        components['schemas']['ChoiceDisplay'] | null
    }
    SubmissionFiles: {
      url?: string
      name?: string
    }[]
    SubmissionAnswers: {
      client?: {
        first_name?: string | null
        last_name?: string | null
        preferred_name?: string | null
        email?: string | null
        date_of_birth?: string | null
        phone_number?: string | null
        gender?: string | null
        centrelink_support?: components['schemas']['BooleanYesNo'] | null
        eligibility_notes?: string | null
        requires_interpreter?: components['schemas']['ChoiceDisplay'] | null
        primary_language_non_english?:
          components['schemas']['BooleanYesNo'] | null
        primary_language?: string | null
        is_aboriginal_or_torres_strait_islander?:
          components['schemas']['ChoiceDisplay'] | null
        number_of_dependents?: number | null
        eligibility_circumstances?:
          components['schemas']['ChoiceDisplay'][] | null
        call_times?: components['schemas']['ChoiceDisplay'][] | null
        special_circumstances?: components['schemas']['ChoiceDisplay'][] | null
      }
      tenancy?: {
        address?: string | null
        suburb?: string | null
        postcode?: string | null
        is_on_lease?: components['schemas']['ChoiceDisplay'] | null
        rental_circumstances?: components['schemas']['ChoiceDisplay'] | null
        start_date?: string | null
        landlord?: components['schemas']['SubmissionPerson'] | null
        agent?: components['schemas']['SubmissionPerson'] | null
      }
      issue?: {
        issues?: components['schemas']['ChoiceDisplay'][] | null
        weekly_income?: number | null
        annual_income_range?: components['schemas']['ChoiceDisplay'] | null
        employment_status?: components['schemas']['ChoiceDisplay'][] | null
        referrer?: string | null
        referrer_type?: components['schemas']['ChoiceDisplay'] | null
        weekly_rent?: number | null
        support_worker?: components['schemas']['SubmissionPerson'] | null
      }
      topic_specific?: {
        REPAIRS?: {
          issue_start?: string | null
          issue_photos?: components['schemas']['SubmissionFiles'] | null
          applied_vcat?: components['schemas']['BooleanYesNo'] | null
          vcat?: components['schemas']['ChoiceDisplay'][] | null
          issue_description?: components['schemas']['BooleanYesNo'] | null
          required?: string[] | null
        } | null
        BONDS?: {
          claim_reasons?: string[] | null
          cleaning_claim_amount?: number | null
          cleaning_claim_description?: string | null
          cleaning_documents?: components['schemas']['SubmissionFiles'] | null
          damage_caused_by_tenant?: components['schemas']['BooleanYesNo'] | null
          damage_claim_amount?: number | null
          damage_claim_description?: string | null
          damage_quote?: components['schemas']['SubmissionFiles'] | null
          has_landlord_made_rtba_application?:
            components['schemas']['BooleanYesNo'] | null
          locks_changed_by_tenant?: components['schemas']['BooleanYesNo'] | null
          locks_claim_amount?: number | null
          locks_change_quote?: components['schemas']['SubmissionFiles'] | null
          money_is_owed_by_tenant?: components['schemas']['BooleanYesNo'] | null
          money_owed_claim_amount?: number | null
          money_owed_claim_description?: string | null
          move_out_date?: string | null
          other_reasons_amount?: number | null
          other_reasons_description?: string | null
          tenant_has_rtba_application_copy?:
            components['schemas']['BooleanYesNo'] | null
          rtba_application?: components['schemas']['SubmissionFiles'] | null
        } | null
        EVICTION_ARREARS?: {
          doc_delivery_time_notice_to_vacate?: string | null
          has_notice?: components['schemas']['BooleanYesNo'] | null
          is_already_removed?: components['schemas']['BooleanYesNo'] | null
          is_unpaid_rent?: components['schemas']['BooleanYesNo'] | null
          is_vcat_date?: components['schemas']['BooleanYesNo'] | null
          notice_send_date?: string | null
          notice_vacate_date?: string | null
          payment_fail_description?: string | null
          payment_fail_reason?: string[] | null
          vcat_date?: string | null
          documents?: components['schemas']['SubmissionFiles'] | null
          can_afford_payment_plan?:
            components['schemas']['ChoiceDisplay'] | null
          documents_provided?: string[] | null
          delivery_method_notice_to_vacate?: string | null
          delivery_method_other_docs?: string | null
          delivery_method_possession_order?: string | null
          doc_delivery_time_other_docs?: string | null
          doc_delivery_time_possession_order?: string | null
          is_on_payment_plan?: components['schemas']['BooleanYesNo'] | null
          miscellaneous?: string | null
          payment_amount?: number | null
          payment_fail_change?: string | null
          rent_cycle?: string | null
          rent_unpaid?: number | null
        } | null
        EVICTION_RETALIATORY?: {
          date_received_ntv?: string | null
          has_notice?: components['schemas']['BooleanYesNo'] | null
          is_already_removed?: components['schemas']['BooleanYesNo'] | null
          ntv_type?: string | null
          retaliatory_reason?: string[] | null
          retaliatory_reason_other?: string | null
          termination_date?: string | null
          vcat_hearing?: components['schemas']['BooleanYesNo'] | null
          vcat_hearing_date?: string | null
          documents?: components['schemas']['SubmissionFiles'] | null
        } | null
        RENT_REDUCTION?: {
          issues?: string[] | null
          issue_description?: string | null
          issue_photos?: components['schemas']['SubmissionFiles'] | null
          issue_start?: string | null
          is_notice_to_vacate?: components['schemas']['BooleanYesNo'] | null
          notice_to_vacate?: components['schemas']['SubmissionFiles'] | null
        } | null
        HEALTH_CHECK?: {
          support_worker_authority?:
            components['schemas']['SubmissionFiles'] | null
          tenancy_documents?: components['schemas']['SubmissionFiles'] | null
        } | null
        OTHER?: {
          issue_description?: string | null
        } | null
      } | null
    }
    Submission: {
      /** Format: uuid */
      id: string
      answers_raw: {
        [key: string]: unknown
      }
      answers: components['schemas']['SubmissionAnswers'] | null
      created_at: string
    }
    IssueBase: {
      topic: string
    }
    TextChoiceListField: {
      display: string
      value: string[]
      choices: string[][]
    }
    User: {
      id: number
      first_name: string
      last_name: string
      /** Format: email */
      email: string
      readonly url: string
      case_capacity: number
      is_intern: boolean
      is_active: boolean
      groups: components['schemas']['TextChoiceListField']
      is_superuser: boolean
      full_name: string
      created_at: string
      is_admin_or_better: boolean
      is_coordinator_or_better: boolean
      is_lawyer_or_better: boolean
      is_paralegal_or_better: boolean
      is_admin: boolean
      is_coordinator: boolean
      is_lawyer: boolean
      is_paralegal: boolean
      is_ms_account_set_up: boolean
      ms_account_created_at: string | null
    }
    TextChoiceField: {
      display: string
      value: string
      choices: string[][]
    }
    Client: {
      /** Format: uuid */
      id: string
      first_name: string
      last_name: string
      email: string
      date_of_birth: string | null
      preferred_name: string | null
      phone_number: string
      gender: string | null
      pronouns: string | null
      centrelink_support: boolean
      eligibility_notes: string
      primary_language_non_english: boolean
      primary_language: string
      number_of_dependents: number | null
      notes: string
      url: string
      age: number | null
      full_name: string
      contact_notes?: string
      contact_restriction: components['schemas']['TextChoiceField']
      requires_interpreter: components['schemas']['TextChoiceField']
      is_aboriginal_or_torres_strait_islander: components['schemas']['TextChoiceField']
      call_times: components['schemas']['TextChoiceListField']
      eligibility_circumstances: components['schemas']['TextChoiceListField']
    }
    PersonBase: {
      full_name: string
    }
    Person: components['schemas']['PersonBase'] & {
      id: number
      email: string
      address: string
      phone_number: string
      url: string
      support_contact_preferences: components['schemas']['TextChoiceField']
    }
    Tenancy: {
      id: number
      address: string
      suburb: string | null
      postcode: string | null
      started: string | null
      url: string
      is_on_lease: components['schemas']['TextChoiceField']
      rental_circumstances: components['schemas']['TextChoiceField']
      landlord: components['schemas']['Person'] | null
      agent: components['schemas']['Person'] | null
    }
    Issue: components['schemas']['IssueBase'] & {
      /** Format: uuid */
      id: string
      topic_display: string
      stage: string
      stage_display: string
      outcome: string | null
      outcome_display: string | null
      outcome_notes: string
      fileref: string
      provided_legal_services: boolean
      is_open: boolean
      is_sharepoint_set_up: boolean
      paralegal: components['schemas']['User'] | null
      lawyer: components['schemas']['User'] | null
      client: components['schemas']['Client']
      employment_status: components['schemas']['TextChoiceListField']
      referrer: string
      referrer_type: components['schemas']['TextChoiceField']
      tenancy: components['schemas']['Tenancy']
      weekly_rent: number | null
      annual_income_range?: components['schemas']['TextChoiceField']
      support_worker: components['schemas']['Person'] | null
      actionstep_id: number | null
      created_at: string
      url: string
      answers: {
        [key: string]: string
      } | null
      is_conflict_check: boolean | null
      is_eligibility_check: boolean | null
      next_review: string | null
      /** Format: uuid */
      submission_id: string | null
    }
    ClientCreate: {
      first_name: string
      last_name: string
      email: string
      date_of_birth?: string | null
      preferred_name?: string | null
      phone_number?: string
      gender?: string | null
      pronouns?: string | null
      centrelink_support?: boolean
      eligibility_notes?: string
      primary_language_non_english?: boolean
      primary_language?: string
      number_of_dependents?: number | null
      notes?: string
      url?: string
      age?: number | null
      full_name?: string
      contact_notes?: string
      contact_restriction?: string
      requires_interpreter?: string
      is_aboriginal_or_torres_strait_islander?: string
      call_times?: string[]
      eligibility_circumstances?: string[]
    }
    TenancyCreate: {
      address: string
      suburb: string | null
      postcode: string | null
      started?: string | null
      is_on_lease?: string
      rental_circumstances?: string
      landlord_id?: number | null
      agent_id?: number | null
    }
    IssueCreate: components['schemas']['IssueBase'] & {
      /**
       * Format: uuid
       * @description One of client_id or client is required.
       */
      client_id?: string
      client?: components['schemas']['ClientCreate']
      /** @description One of tenancy_id or tenancy is required. */
      tenancy_id?: number
      tenancy?: components['schemas']['TenancyCreate']
      stage?: string
      outcome?: string | null
      outcome_notes?: string
      provided_legal_services?: boolean
      paralegal_id?: number | null
      lawyer_id?: number | null
      support_worker_id?: number | null
      employment_status?: string
      annual_income_range?: string | null
      referrer?: string
      referrer_type?: string
      weekly_rent?: number | null
    }
    IssueNoteCreator: {
      id: number
      first_name: string
      last_name: string
      email: string
      full_name: string
      url: string
    }
    IssueNote: {
      id: number
      note_type: string
      text: string
      event: string | null
      creator: components['schemas']['IssueNoteCreator']
      text_display: string
      created_at: string
      reviewee: components['schemas']['User'] | null
    }
    IssueUpdate: {
      topic?: string
      stage?: string
      is_open?: boolean
      outcome?: string | null
      outcome_notes?: string
      provided_legal_services?: boolean
      paralegal_id?: number | null
      lawyer_id?: number | null
      support_worker_id?: number | null
      weekly_rent?: number | null
      employment_status?: string
      annual_income_range?: string | null
      referrer?: string
      referrer_type?: string
    }
    IssueNoteCreate: {
      note_type: string
      text: string
      event?: string | null
    }
    SharepointDocument: {
      name: string
      url: string
      id: string
      size: number
      is_file: boolean
    }
    /** @enum {string} */
    ServiceCategory: 'DISCRETE' | 'ONGOING'
    /** @enum {string} */
    ServiceTypeDiscrete:
      | 'LEGAL_ADVICE'
      | 'LEGAL_TASK'
      | 'GENERAL_INFORMATION'
      | 'GENERAL_REFERRAL_SIMPLE'
      | 'GENERAL_REFERRAL_FACILITATED'
    /** @enum {string} */
    ServiceTypeOngoing:
      'LEGAL_SUPPORT' | 'REPRESENTATION_COURT_TRIBUNAL' | 'REPRESENTATION_OTHER'
    Service: {
      id: number
      /** Format: uuid */
      issue_id: string
      category: components['schemas']['ServiceCategory']
      type:
        | components['schemas']['ServiceTypeDiscrete']
        | components['schemas']['ServiceTypeOngoing']
      started_at: string
      finished_at: string | null
      count: number | null
      notes: string | null
    }
    ServiceCreate: {
      category: components['schemas']['ServiceCategory']
      type:
        | components['schemas']['ServiceTypeDiscrete']
        | components['schemas']['ServiceTypeOngoing']
      started_at: string
      finished_at: string | null
      count: number | null
      notes: string | null
    }
    ServiceUpdate: {
      category?: components['schemas']['ServiceCategory']
      type?:
        | components['schemas']['ServiceTypeDiscrete']
        | components['schemas']['ServiceTypeOngoing']
      started_at?: string
      finished_at?: string | null
      count?: number | null
      notes?: string | null
    }
    EmailCreate: {
      to_address: string
      cc_addresses: string[]
      subject: string
      text: string
      html: string
      state?: string
    }
    EmailAttachment: {
      id: number
      url: string
      name: string
      sharepoint_state: string
      content_type: string
      email: number
    }
    Email: components['schemas']['EmailCreate'] & {
      id: number
      /** Format: uuid */
      issue: string
      from_address: string
      created_at: string
      processed_at: string | null
      sender: components['schemas']['User']
      state: string
      reply_url: string
      edit_url: string
      attachments: components['schemas']['EmailAttachment'][]
    }
    EmailThread: {
      emails: components['schemas']['Email'][]
      subject: string
      slug: string
      most_recent: string
      url: string
    }
    EmailUpdate: {
      to_address?: string
      cc_addresses?: string[]
      subject?: string
      text?: string
      html?: string
      state?: string
    }
    EmailAttachmentCreate: {
      /** Format: binary */
      file: string
    }
    /** @enum {string} */
    IssueNoteType:
      | 'CONFLICT_CHECK_FAILURE'
      | 'CONFLICT_CHECK_SUCCESS'
      | 'ELIGIBILITY_CHECK_FAILURE'
      | 'ELIGIBILITY_CHECK_SUCCESS'
      | 'EMAIL'
      | 'EVENT'
      | 'PARALEGAL'
      | 'PERFORMANCE'
      | 'REVIEW'
    PersonCreate: components['schemas']['PersonBase'] & {
      email?: string
      address?: string
      phone_number?: string
      support_contact_preferences?: string
    }
    /** @enum {string} */
    IssueDateType:
      | 'FILING_DEADLINE'
      | 'HEARING_LISTED'
      | 'LIMITATION'
      | 'NTV_TERMINATION'
      | 'OTHER'
    /** @enum {string} */
    IssueDateHearingType: 'IN_PERSON' | 'VIRTUAL'
    IssueDate: {
      id: number
      type: components['schemas']['IssueDateType']
      date: string
      hearing_type?: components['schemas']['IssueDateHearingType']
      hearing_location?: string
      issue: components['schemas']['Issue']
      notes: string
      is_reviewed: boolean
    }
    IssueDateCreate: {
      type: components['schemas']['IssueDateType']
      date: string
      /** Format: uuid */
      issue_id: string
      hearing_type?: components['schemas']['IssueDateHearingType']
      hearing_location?: string
      notes?: string
      is_reviewed?: boolean
    }
    IssueDateUpdate: {
      type?: components['schemas']['IssueDateType']
      date?: string
      /** Format: uuid */
      issue_id?: string
      hearing_type?: components['schemas']['IssueDateHearingType']
      hearing_location?: string
      notes?: string
      is_reviewed?: boolean
    }
    TenancyUpdate: {
      address?: string
      suburb?: string | null
      postcode?: string | null
      started?: string | null
      is_on_lease?: string
      rental_circumstances?: string
      landlord_id?: number | null
      agent_id?: number | null
    }
    ClientUpdate: {
      first_name?: string
      last_name?: string
      email?: string
      date_of_birth?: string | null
      preferred_name?: string | null
      phone_number?: string
      gender?: string | null
      pronouns?: string | null
      centrelink_support?: boolean
      eligibility_notes?: string
      primary_language_non_english?: boolean
      primary_language?: string
      number_of_dependents?: number | null
      notes?: string
      url?: string
      age?: number | null
      full_name?: string
      contact_notes?: string
      contact_restriction?: string
      requires_interpreter?: string
      is_aboriginal_or_torres_strait_islander?: string
      call_times?: string[]
      eligibility_circumstances?: string[]
    }
    UserCreate: {
      first_name: string
      last_name: string
      /** Format: email */
      email: string
      readonly url: string
      groups: string[]
    }
    UserUpdate: {
      first_name?: string
      last_name?: string
      /** Format: email */
      email?: string
      readonly url?: string
      groups?: string[]
    }
    MicrosoftUserPermissions: {
      /** @enum {string} */
      access_level: 'FULL_ACCESS' | 'PARTIAL_ACCESS' | 'NO_ACCESS'
      issues_with_access: components['schemas']['Issue'][]
      issues_without_access: components['schemas']['Issue'][]
    }
    EmailTemplateCreate: {
      name: string
      topic: string
      subject: string
      text: string
    }
    EmailTemplate: components['schemas']['EmailTemplateCreate'] & {
      id: number
      url: string
      created_at: string
    }
    NotificationTemplateBase: {
      name: string
      topic: string
      event_stage: string
      raw_text: string
      message_text: string
    }
    NotificationTemplate: components['schemas']['NotificationTemplateBase'] & {
      id: number
      url: string
      created_at: string
      event: components['schemas']['TextChoiceField']
      channel: components['schemas']['TextChoiceField']
      target: components['schemas']['TextChoiceField']
    }
    NotificationTemplateCreate: components['schemas']['NotificationTemplateBase'] & {
      event: string
      channel: string
      target: string
    }
    DocumentTemplate: {
      id: number
      name: string
      topic: string
      url: string
      created_at: string
      modified_at: string
    }
    DocumentTemplateCreate: {
      topic: string
      files: string[]
    }
    DocumentTemplateRename: {
      name: string
    }
  }
  responses: {
    /** @description Bad request */
    BadRequest: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description Permission Denied */
    PermissionDenied: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description The requested resource was not found */
    NotFound: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
    /** @description The specific resource was deleted successfully */
    NoContent: {
      headers: {
        [name: string]: unknown
      }
      content?: never
    }
  }
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  createIntakeSubmission: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['IntakeSubmissionCreate']
      }
    }
    responses: {
      /** @description Successful response. */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IntakeSubmission']
        }
      }
      400: components['responses']['BadRequest']
    }
  }
  getIntakeSubmission: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Submission ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IntakeSubmission']
        }
      }
      403: components['responses']['PermissionDenied']
      404: components['responses']['NotFound']
    }
  }
  updateIntakeSubmission: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Submission ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['IntakeSubmissionCreate']
      }
    }
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IntakeSubmission']
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
      404: components['responses']['NotFound']
    }
  }
  submitIntakeSubmission: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Submission ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': Record<string, never>
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
      404: components['responses']['NotFound']
    }
  }
  createIntakeUpload: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'multipart/form-data': {
          /** Format: binary */
          file: string
          /** Format: uuid */
          issue?: string
        }
      }
    }
    responses: {
      /** @description Successful response. */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IntakeFileUpload']
        }
      }
      400: components['responses']['BadRequest']
    }
  }
  createIntakeNoEmailContact: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': {
          name: string
          phone_number: string
        }
      }
    }
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': Record<string, never>
        }
      }
      400: components['responses']['BadRequest']
    }
  }
  getSubmission: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Submission ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Submission']
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
      404: components['responses']['NotFound']
    }
  }
  getCases: {
    parameters: {
      query?: {
        page?: number
        page_size?: number
        search?: string
        topic?: string
        stage?: string
        outcome?: string
        is_open?: string
        paralegal?: string
        lawyer?: string
        client?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            current: number
            next: number | null
            prev: number | null
            page_count: number
            item_count: number
            results: components['schemas']['Issue'][]
          }
        }
      }
    }
  }
  createCase: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['IssueCreate']
      }
    }
    responses: {
      /** @description Successful response. */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Issue']
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  getCase: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Entity ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            issue: components['schemas']['Issue']
            tenancy: components['schemas']['Tenancy']
            notes: components['schemas']['IssueNote'][]
          }
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  updateCase: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Entity ID */
        id: string
      }
      cookie?: never
    }
    /** @description Successful response. */
    requestBody: {
      content: {
        'application/json': components['schemas']['IssueUpdate']
      }
    }
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Issue']
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  createCaseNote: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Entity ID */
        id: string
      }
      cookie?: never
    }
    /** @description Successful response. */
    requestBody: {
      content: {
        'application/json': components['schemas']['IssueNoteCreate']
      }
    }
    responses: {
      /** @description Successful response. */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IssueNote']
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  getCaseDocuments: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Entity ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            sharepoint_url: string
            documents: components['schemas']['SharepointDocument'][]
          }
        }
      }
    }
  }
  getCaseServices: {
    parameters: {
      query?: {
        category?: components['schemas']['ServiceCategory']
        type?:
          | components['schemas']['ServiceTypeDiscrete']
          | components['schemas']['ServiceTypeOngoing']
      }
      header?: never
      path: {
        /** @description Entity ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Service'][]
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  createCaseService: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Entity ID */
        id: string
      }
      cookie?: never
    }
    /** @description Successful response. */
    requestBody: {
      content: {
        'application/json': components['schemas']['ServiceCreate']
      }
    }
    responses: {
      /** @description Successful response. */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Service']
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  getCaseService: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Case ID */
        id: string
        /** @description Service ID */
        service_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Service']
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  deleteCaseService: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Case ID */
        id: string
        /** @description Service ID */
        service_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      204: components['responses']['NoContent']
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  updateCaseService: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Case ID */
        id: string
        /** @description Service ID */
        service_id: number
      }
      cookie?: never
    }
    /** @description Request body for updating a case service. */
    requestBody: {
      content: {
        'application/json': components['schemas']['ServiceUpdate']
      }
    }
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Service']
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  getEmailThreads: {
    parameters: {
      query?: {
        slug?: string
      }
      header?: never
      path: {
        /** @description Case ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EmailThread'][]
        }
      }
    }
  }
  createEmail: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Case ID */
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailCreate']
      }
    }
    responses: {
      /** @description Successful response. */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Email']
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  getEmail: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Case ID */
        id: string
        /** @description Email ID */
        email_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Email']
        }
      }
    }
  }
  deleteEmail: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Case ID */
        id: string
        /** @description Email ID */
        email_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      204: components['responses']['NoContent']
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  updateEmail: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Case ID */
        id: string
        /** @description Email ID */
        email_id: number
      }
      cookie?: never
    }
    /** @description Successful response. */
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailUpdate']
      }
    }
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Email']
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  createEmailAttachment: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Case ID */
        id: string
        /** @description Email ID */
        email_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['EmailAttachmentCreate']
      }
    }
    responses: {
      /** @description Successful response. */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EmailAttachment']
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  deleteEmailAttachment: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Case ID */
        id: string
        /** @description Email ID */
        email_id: number
        /** @description Email Attachment ID */
        attachment_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      204: components['responses']['NoContent']
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  uploadEmailAttachmentToSharepoint: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Case ID */
        id: string
        /** @description Email ID */
        email_id: number
        /** @description Email Attachment ID */
        attachment_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      204: components['responses']['NoContent']
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  downloadEmailAttachmentFromSharepoint: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Case ID */
        id: string
        /** @description Email ID */
        email_id: number
        /** @description Sharepoint ID */
        sharepoint_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      204: components['responses']['NoContent']
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  getNotes: {
    parameters: {
      query?: {
        page?: number
        page_size?: number
        /** @description Entity ID */
        issue?: string
        /** @description Creator account ID */
        creator?: number
        note_type?: components['schemas']['IssueNoteType']
        /** @description Reviewee account ID */
        reviewee?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            current: number
            next: number | null
            prev: number | null
            page_count: number
            item_count: number
            results: components['schemas']['IssueNote'][]
          }
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  getPeople: {
    parameters: {
      query?: {
        query?: string
        /** @description Page number (pagination) */
        page?: number
        /** @description Number of items per page (pagination) */
        page_size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            current: number
            next: number | null
            prev: number | null
            page_count: number
            item_count: number
            results: components['schemas']['Person'][]
          }
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  createPerson: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PersonCreate']
      }
    }
    responses: {
      /** @description Successful response. */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Person']
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  getPerson: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Entity ID */
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Person']
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  deletePerson: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Entity ID */
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      204: components['responses']['NoContent']
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  updatePerson: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Entity ID */
        id: number
      }
      cookie?: never
    }
    /** @description Successful response. */
    requestBody: {
      content: {
        'application/json': components['schemas']['PersonCreate']
      }
    }
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Person']
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  getCaseDates: {
    parameters: {
      query?: {
        page?: number
        page_size?: number
        q?: string
        /** @description Entity ID */
        issue_id?: string
        type?: components['schemas']['IssueDateType']
        is_reviewed?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            current: number
            next: number | null
            prev: number | null
            page_count: number
            item_count: number
            results: components['schemas']['IssueDate'][]
          }
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  createCaseDate: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description Successful response. */
    requestBody: {
      content: {
        'application/json': components['schemas']['IssueDateCreate']
      }
    }
    responses: {
      /** @description Successful response. */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IssueDate']
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  getCaseDate: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Date ID */
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IssueDate']
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  deleteCaseDate: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Date ID */
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      204: components['responses']['NoContent']
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  updateCaseDate: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Date ID */
        id: number
      }
      cookie?: never
    }
    /** @description Request body for updating a case date. */
    requestBody: {
      content: {
        'application/json': components['schemas']['IssueDateUpdate']
      }
    }
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IssueDate']
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  getTenancy: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Entity ID */
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Tenancy']
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  updateTenancy: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Entity ID */
        id: number
      }
      cookie?: never
    }
    /** @description Request body for updating a tenancy. */
    requestBody: {
      content: {
        'application/json': components['schemas']['TenancyUpdate']
      }
    }
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Tenancy']
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  getClients: {
    parameters: {
      query?: {
        page?: number
        page_size?: number
        q?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            current: number
            next: number | null
            prev: number | null
            page_count: number
            item_count: number
            results: components['schemas']['Client'][]
          }
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  getClient: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Entity ID */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Client']
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  updateClient: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Entity ID */
        id: string
      }
      cookie?: never
    }
    /** @description Successful response. */
    requestBody: {
      content: {
        'application/json': components['schemas']['ClientUpdate']
      }
    }
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Client']
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  getUsers: {
    parameters: {
      query?: {
        page?: number
        page_size?: number
        name?: string
        group?: string
        is_active?: boolean
        sort?:
          | 'case_capacity'
          | '-case_capacity'
          | 'date_joined'
          | '-date_joined'
          | 'email'
          | '-email'
          | 'first_name'
          | '-first_name'
          | 'last_name'
          | '-last_name'
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            current: number
            next: number | null
            prev: number | null
            page_count: number
            item_count: number
            results: components['schemas']['User'][]
          }
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  createUser: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UserCreate']
      }
    }
    responses: {
      /** @description Successful response. */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserCreate']
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  getUser: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Entity ID */
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  updateUser: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Entity ID */
        id: number
      }
      cookie?: never
    }
    /** @description Successful response. */
    requestBody: {
      content: {
        'application/json': components['schemas']['UserUpdate']
      }
    }
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  getUserAccountPermissions: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Entity ID */
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MicrosoftUserPermissions']
        }
      }
    }
  }
  resyncUserAccountPermissions: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Entity ID */
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            account: components['schemas']['User']
            permissions: components['schemas']['MicrosoftUserPermissions']
          }
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  getPotentialUsers: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** Format: email */
            email: string
            first_name: string
            last_name: string
          }[]
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  getEmailTemplates: {
    parameters: {
      query?: {
        name?: string
        topic?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EmailTemplate'][]
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  createEmailTemplate: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailTemplateCreate']
      }
    }
    responses: {
      /** @description Successful response. */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EmailTemplate']
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  getEmailTemplate: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Entity ID */
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EmailTemplate']
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  deleteEmailTemplate: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Entity ID */
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      204: components['responses']['NoContent']
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  updateEmailTemplate: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Entity ID */
        id: number
      }
      cookie?: never
    }
    /** @description Successful response. */
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailTemplateCreate']
      }
    }
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EmailTemplate']
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  getNotificationTemplates: {
    parameters: {
      query?: {
        name?: string
        topic?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['NotificationTemplate'][]
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  createNotificationTemplate: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['NotificationTemplateCreate']
      }
    }
    responses: {
      /** @description Successful response. */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['NotificationTemplate']
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  getNotificationTemplate: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Entity ID */
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['NotificationTemplate']
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  deleteNotificationTemplate: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Entity ID */
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      204: components['responses']['NoContent']
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  updateNotificationTemplate: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Entity ID */
        id: number
      }
      cookie?: never
    }
    /** @description Successful response. */
    requestBody: {
      content: {
        'application/json': components['schemas']['NotificationTemplateCreate']
      }
    }
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['NotificationTemplate']
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  getDocumentTemplates: {
    parameters: {
      query?: {
        name?: string
        topic?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful response. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DocumentTemplate'][]
        }
      }
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  createDocumentTemplate: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['DocumentTemplateCreate']
      }
    }
    responses: {
      201: components['responses']['NoContent']
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  deleteDocumentTemplate: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Entity ID */
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      204: components['responses']['NoContent']
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
  renameDocumentTemplate: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Entity ID */
        id: number
      }
      cookie?: never
    }
    /** @description Successful response. */
    requestBody: {
      content: {
        'application/json': components['schemas']['DocumentTemplateRename']
      }
    }
    responses: {
      204: components['responses']['NoContent']
      400: components['responses']['BadRequest']
      403: components['responses']['PermissionDenied']
    }
  }
}
