# Generated by Django 4.0.7 on 2022-09-28 02:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('topic', models.CharField(choices=[('GENERAL', 'General'), ('REPAIRS', 'Repairs'), ('BONDS', 'Bonds'), ('EVICTION', 'Eviction')], max_length=32)),
                ('event', models.CharField(choices=[('STAGE_CHANGE', 'Stage changed')], max_length=32)),
                ('channel', models.CharField(choices=[('SLACK', 'Send a Slack message')], max_length=32)),
                ('target', models.CharField(choices=[('PARALEGAL', 'Assigned paralegal'), ('LAWYER', 'Assigned lawyer')], max_length=32)),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
