# Generated by Django 4.0.7 on 2022-09-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='name',
            field=models.CharField(default='qsqqwss', max_length=64),
            preserve_default=False,
        ),
    ]
