# Generated by Django 4.0.7 on 2022-11-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0003_notification_event_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='text',
            new_name='raw_text',
        ),
        migrations.AddField(
            model_name='notification',
            name='message_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
