# Generated by Django 4.0.9 on 2023-04-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0004_rename_text_notification_raw_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='topic',
            field=models.CharField(choices=[('GENERAL', 'General'), ('HEALTH_CHECK', 'Housing Health Check'), ('REPAIRS', 'Repairs'), ('BONDS', 'Bonds'), ('EVICTION', 'Eviction')], max_length=32),
        ),
    ]
