# Generated by Django 5.1.1 on 2025-04-14 03:04

from django.db import migrations, models


def _migrate_legacy_eviction_value(apps, schema_editor):
    Notification = apps.get_model("notify", "Notification")
    Notification.objects.filter(topic="EVICTION").update(topic="EVICTION_ARREARS")


class Migration(migrations.Migration):
    dependencies = [
        ("notify", "0006_alter_notification_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="topic",
            field=models.CharField(
                choices=[
                    ("GENERAL", "General"),
                    ("REPAIRS", "Repairs"),
                    ("BONDS", "Bonds"),
                    ("EVICTION_ARREARS", "Eviction (Arrears)"),
                    ("HEALTH_CHECK", "Housing Health Check"),
                ],
                max_length=32,
            ),
        ),
        migrations.RunPython(
            _migrate_legacy_eviction_value,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
