# Generated by Django 4.0.10 on 2023-12-11 05:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import office.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClosureTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('call_text', models.TextField(default=office.models.ClosureTemplate._get_call_default)),
                ('email_html', models.TextField(default=office.models.ClosureTemplate._get_email_default)),
                ('notice_html', models.TextField(default=office.models.ClosureTemplate._get_notice_default)),
            ],
        ),
        migrations.CreateModel(
            name='Closure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('call_audio', models.FileField(blank=True, null=True, storage=office.models.Closure._get_storage, upload_to=office.models.Closure._get_file_name)),
                ('template', models.ForeignKey(default=office.models.Closure._get_template_default, on_delete=django.db.models.deletion.CASCADE, to='office.closuretemplate')),
            ],
        ),
    ]
