import { IntakeQuestion, NONE_OF_THE_ABOVE } from '../form/types'

export const IMPACT_QUESTIONS: IntakeQuestion[] = [
  {
    name: 'IMPACT_INTRO',
    required: false,
    type: 'DISPLAY',
    html: '<h2>Great job. That is all the questions we have about your landlord. Finally, we just need a few details about you.</h2><p>These details will help us to better understand who you are and when we can contact you.</p>',
  },
  {
    name: 'DOB',
    required: true,
    type: 'DATE',
    title: 'What is your date of birth?',
  },
  {
    name: 'GENDER',
    required: true,
    type: 'CHOICE_SINGLE_TEXT',
    colCount: 2,
    choices: [
      { value: 'MALE', text: 'Male' },
      { value: 'FEMALE', text: 'Female' },
      { value: 'SISTERGIRL', text: 'Sistergirl' },
      { value: 'BROTHERBOY', text: 'Brotherboy' },
      { value: 'NON_BINARY', text: 'Non-binary' },
      { value: 'GENDER_DIVERSE', text: 'Gender diverse' },
      { value: 'OMITTED', text: 'Prefer not to say' },
    ],
    placeholder: 'Prefer to self-describe',
    title: 'What gender do you identify as?',
  },
  {
    name: 'IS_ABORIGINAL_OR_TORRES_STRAIT_ISLANDER',
    required: true,
    type: 'CHOICE_SINGLE',
    colCount: 2,
    choices: [
      { value: 'NO', text: 'No' },
      { value: 'YES_ABORIGINAL', text: 'Yes, Aboriginal' },
      { value: 'YES_TSI', text: 'Yes, Torres Strait Islander' },
      {
        value: 'YES_ABORIGINAL_AND_TSI',
        text: 'Yes, Aboriginal and Torres Strait Islander',
      },
      { value: 'PREFER_NOT_TO_ANSWER', text: 'Prefer not to answer' },
      { value: 'NOT_STATED', text: 'Not Stated' },
    ],
    title:
      'Do you identify as an Aboriginal and/or Torres Strait Islander person?',
  },
  {
    name: 'CAN_SPEAK_NON_ENGLISH',
    required: true,
    type: 'CHOICE_SINGLE',
    choices: [
      { value: true, text: 'Yes' },
      { value: false, text: 'No' },
    ],
    title: 'Do you speak a <strong>first language</strong> other than English?',
  },
  {
    name: 'INTERPRETER',
    required: true,
    type: 'CHOICE_SINGLE',
    title: 'Do you need an interpreter?',
    visibleIf: '{CAN_SPEAK_NON_ENGLISH} = true',
    choices: [
      { value: 'NO', text: 'No' },
      { value: 'YES_WRITTEN', text: 'Yes (written communication)' },
      { value: 'YES_SPOKEN', text: 'Yes (spoken communication)' },
      { value: 'YES_WRITTEN_SPOKEN', text: 'Yes (written and spoken)' },
      { value: 'UNKNOWN', text: 'Unknown' },
    ],
  },
  {
    name: 'FIRST_LANGUAGE',
    required: true,
    type: 'TEXT',
    maxLength: 64,
    title:
      'What is your <strong>preferred language</strong> other than English?',
    visibleIf: '{CAN_SPEAK_NON_ENGLISH} = true',
  },
  {
    name: 'WORK_OR_STUDY_CIRCUMSTANCES',
    required: true,
    title: 'Which best describes your work or study situation?',
    type: 'CHOICE_SINGLE',
    colCount: 2,
    choices: [
      { value: 'WORKING_FULL_TIME', text: 'Working full time' },
      { value: 'WORKING_PART_TIME', text: 'Working part time' },
      { value: 'WORKING_CASUALLY', text: 'Working casually' },
      { value: 'WORKING_TEMPORARY', text: 'Temporary work' },
      { value: 'STUDENT', text: 'Student' },
      { value: 'APPRENTICE', text: 'Apprentice or trainee' },
      { value: 'RETIRED', text: 'Retired' },
      { value: 'PARENT', text: 'Full time parent' },
      { value: 'TEMPORARILY_UNABLE', text: 'Temporarily unable to work' },
      { value: 'LOOKING_FOR_WORK', text: 'Looking for work' },
      { value: 'NOT_LOOKING_FOR_WORK', text: 'Not looking for work' },
      { value: NONE_OF_THE_ABOVE, text: 'None of the above' },
    ],
  },
  {
    name: 'REFERRER_TYPE',
    required: true,
    title: 'How did you hear about Anika?',
    type: 'CHOICE_SINGLE',
    colCount: 2,
    choices: [
      { value: 'LEGAL_CENTRE', text: 'Legal centre' },
      { value: 'HOUSING_SERVICE', text: 'Housing service' },
      { value: 'COMMUNITY_ORGANISATION', text: 'Community Organisation' },
      { value: 'SOCIAL_MEDIA', text: 'Social media' },
      { value: 'SEARCH', text: 'Google search' },
      { value: 'WORD_OF_MOUTH', text: 'Word of mouth' },
      { value: 'ONLINE_AD', text: 'Online ad' },
      { value: 'RADIO', text: 'Radio' },
      { value: 'BILLBOARD', text: 'Billboard' },
      { value: 'POSTER', text: 'Poster' },
      { value: 'RETURNING_CLIENT', text: 'Returning client' },
    ],
  },
  {
    name: 'LEGAL_CENTRE_REFERRER',
    required: true,
    visibleIf: "{REFERRER_TYPE} = 'LEGAL_CENTRE'",
    title: 'Which legal centre referred you?',
    type: 'CHOICE_SINGLE',
    colCount: 2,
    choices: [
      { value: 'Tenants Victoria', text: 'Tenants Victoria' },
      { value: 'Victoria Legal Aid', text: 'Victoria Legal Aid' },
      { value: 'Justice Connect', text: 'Justice Connect' },
      {
        value: 'Consumer Affairs Victoria',
        text: 'Consumer Affairs Victoria',
      },
      {
        value: 'Asylum Seeker Resource Centre',
        text: 'Asylum Seeker Resource Centre',
      },
      { value: 'Other', text: 'Other' },
    ],
  },
  {
    name: 'HOUSING_SERVICE_REFERRER',
    visibleIf: "{REFERRER_TYPE} = 'HOUSING_SERVICE'",
    required: true,
    title: 'Which housing service referred you?',
    type: 'CHOICE_SINGLE',
    colCount: 2,
    choices: [
      { value: 'Launch Housing', text: 'Launch Housing' },
      { value: 'Quantum', text: 'Quantum' },
      { value: 'Women’s Housing', text: 'Women’s Housing' },
      { value: 'Rental and Housing Union', text: 'Rental and Housing Union' },
      { value: 'Better Renting', text: 'Better Renting' },
      { value: 'Tenants Victoria', text: 'Tenants Victoria' },
      { value: 'Other', text: 'Other' },
    ],
  },
  {
    name: 'COMMUNITY_ORGANISATION_REFERRER',
    visibleIf: "{REFERRER_TYPE} = 'COMMUNITY_ORGANISATION'",
    required: true,
    title: 'Which community organisation referred you?',
    type: 'CHOICE_SINGLE',
    colCount: 2,
    choices: [
      {
        value: 'Council of Single Mothers and their Children',
        text: 'Council of Single Mothers and their Children',
      },
      {
        value: 'Ethnic Communities Council of Victoria',
        text: 'Ethnic Communities Council of Victoria',
      },
      { value: 'Jewish Care', text: 'Jewish Care' },
      { value: 'Sacred Heart Mission', text: 'Sacred Heart Mission' },
      { value: 'St Vincent De Paul', text: 'St Vincent De Paul' },
      { value: 'Tenants Victoria', text: 'Tenants Victoria' },
      { value: 'Other', text: 'Other' },
    ],
  },
  {
    name: 'SOCIAL_REFERRER',
    visibleIf: "{REFERRER_TYPE} = 'SOCIAL_MEDIA'",
    required: true,
    title: 'Which social media site did you find us on?',
    type: 'CHOICE_SINGLE',
    colCount: 2,
    choices: [
      { value: 'Facebook', text: 'Facebook' },
      { value: 'Instagram', text: 'Instagram' },
      { value: 'Twitter', text: 'Twitter' },
      { value: 'LinkedIn', text: 'LinkedIn' },
      { value: 'Pinterest', text: 'Pinterest' },
      { value: 'Reddit', text: 'Reddit' },
      { value: 'Other', text: 'Other' },
    ],
  },
]
