name: CI
on:
  push:
    branches:
      - hub

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t clerk:latest -f docker/Dockerfile .
      - name: Run tests
        run: docker-compose -f docker/docker-compose.local.yml run --rm test  pytest -s -vv
