name: Deploy
on:
  - workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo from GitHub
      - uses: actions/checkout@v2
      # Set envars for deployment.
      - name: Set env vars
        run: |
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
              echo -e "\n>>> Using production envars."
              echo "COMPOSE_SUFFIX=prod" >> $GITHUB_ENV
              echo "PROJECT=clerk" >> $GITHUB_ENV
          else
              echo -e "\n>>> Using staging envars."
              echo "COMPOSE_SUFFIX=staging" >> $GITHUB_ENV
              echo "PROJECT=clerk_test" >> $GITHUB_ENV
          fi
      - name: Run deploy script
        run: ./scripts/deploy/deploy.sh
        shell: bash
        env:
          CLERK_PRIVATE_SSH_KEY: ${{ secrets.CLERK_PRIVATE_SSH_KEY }}
