name: Deploy Application
on: [workflow_dispatch]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set variables
              run: |
              if [ "${{ github.ref }}" == "refs/heads/develop"]; then
                echo "we are on develop branch"
              else
                echo "we are on another branch"
              fi
            - name: Run deploy script
              run: ./scripts/deploy/deploy.sh
              shell: bash