name: Deploy Application
on: [workflow_dispatch]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set variables
              run: |
              if [ "${{ github.ref }}" = "refs/heads/master" ]; then
                  echo "::set-env name=COMPOSE_SUFFIX::prod"
              elif [ "${{ github.ref }}" = "refs/heads/develop" ]; then
                  echo "::set-env name=COMPOSE_SUFFIX::staging"
              else
                  echo "Please specify either master (prod) or develop (staging) branch"
                  exit 1
              fi
            - name: Run deploy script
              run: ./scripts/deploy/deploy.sh
              shell: bash