name: Deploy Application
on: [workflow_dispatch]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set variables
              run: |
              if [ "${{ github.ref }}" = "refs/heads/develop" ]; then
                  echo "using develop branch"
              else
                  echo "using prod branch"
              fi