name: Deploy Application
on: [workflow_dispatch]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set variables
              run: |
              if [ "${{ github.ref }}" = "refs/heads/develop" ]; then
              else
                  echo "Please select develop (staging) or master (prod) branch"
                  exit 1
              fi
            - name: Run deploy script
              run: ./scripts/deploy/deploy.sh
              shell: bash