name: Staging
on:
  workflow_dispatch:
jobs:
  update_staging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

      # Setup transcrypt so that we can read secrets
    - name: Checkout transcrypt
      uses: actions/checkout@v4
      with:
        repository: elasticdog/transcrypt
        path: transcrypt

    - name: Initialise transcrypt
      run: ./transcrypt/transcrypt -c aes-256-cbc -p '${{ secrets.TRANSCRYPT_PASSWORD }}' --yes

    - name: Update staging
      run: ./infra/staging/database-restore.sh
      shell: bash
      env:
        CLERK_PRIVATE_SSH_KEY: ${{ secrets.CLERK_PRIVATE_SSH_KEY }}
  backup:
    runs-on: ubuntu-latest
    needs: update_staging
    steps:
    - uses: actions/checkout@v4

    - name: Run backup script
      run: ./infra/staging/backup.sh
      shell: bash
      env:
        CLERK_PRIVATE_SSH_KEY: ${{ secrets.CLERK_PRIVATE_SSH_KEY }}
